/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface App404PageNotFound {}
  interface AppBlogFilter {
    'excludedTracks': string[];
  }
  interface AppEntryMeta {
    'header': any;
  }
  interface AppPhotoCard {
    'imagePath': string;
    'item': any;
  }
  interface AppPhotos {
    'name': string;
  }
  interface AppRoot {}
  interface AppTabs {}
  interface Page7QuintessentialBrushesForZbrushBeginners {}
  interface Page7ReasonsWhyTypescriptHelpsYouKickAss {}
  interface PageAJavascriptImplementationOfJavaUtilMap {}
  interface PageAbout {}
  interface PageApplyDifferentMaterialsToSubtoolsInZbrush {}
  interface PageArt {}
  interface PageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnother {}
  interface PageBendThingsInZbrushWithTheBendCurveModifier {}
  interface PageBooks {}
  interface PageCage {}
  interface PageChangeCanvasBackgroundColorInZbrush {}
  interface PageCmdChronBeaverCage {}
  interface PageConfluencePanelMacro {}
  interface PageConvertZbrushPolygroupsIntoSubtools {}
  interface PageCopyAssetsFromNodeModulesInStencilJs {}
  interface PageCreateClothingInZbrushExtrudingMaskedArea {}
  interface PageCreateNewSubtoolFromMaskedAreaInZbrush {}
  interface PageCreatePlayerHealthStatusIndicatorForUnityGuiPart1 {}
  interface PageCreatePlayerHealthStatusIndicatorForUnityGuiPart2 {}
  interface PageCreatePlayerHealthStatusIndicatorForUnityGuiPart3 {}
  interface PageCreatePolygroupFromMaskInZbrush {}
  interface PageDeleteHiddenGeometryInZbrush {}
  interface PageDockerCheatSheet {}
  interface PageFemaleAnatomyOutOfTheBoxInZbrush {}
  interface PageFindJavaClassesOrPackagesContainedInJarFiles {}
  interface PageFixForGitAfterMacosMojaveUpgrade {}
  interface PageFormatCurrencyInAngular {}
  interface PageGettingPartsOfAUrlFromTheHttpservletrequestObject {}
  interface PageHome {}
  interface PageHowToApplyTextureInZbrush {}
  interface PageHowToSketchWithZspheresInZbrush {}
  interface PageHowToUseLiveBooleanInZbrush {}
  interface PageIndexOfItemWithinAngularNgforLoop {}
  interface PageInstallJavaPluginFor64bitFirefoxOnCentos64 {}
  interface PageInstallOracleJava8OnUbuntu {}
  interface PageIsolateAPolygroupInZbrush {}
  interface PageKillingKittens {}
  interface PageLifeEvents {}
  interface PageListIbmDb2Commands {}
  interface PageLoggingWithSpringBoot {}
  interface PageMakeAZbrushSpeedSculptTimelapseVideo {}
  interface PageMappingToAViewInSpringWhenNoControllerLogicIsRequired {}
  interface PageMirrorPolygroupOnSubtoolInZbrush {}
  interface PagePhotosWeaponsPlatoon {}
  interface PagePinkHearts {}
  interface PagePwaWithIonicAngularWordpressApi1 {}
  interface PagePwaWithIonicAngularWordpressApi2 {}
  interface PagePwaWithIonicAngularWordpressApi3 {}
  interface PagePwaWithIonicAngularWordpressApi4 {}
  interface PagePwaWithIonicAngularWordpressApi5 {}
  interface PageQuickAndSimpleCachingWithApacheCommonsJcs {}
  interface PageRayKelleySilverStar {}
  interface PageRdfSyntaxExamples {}
  interface PageRenderTheKeysAndValuesFromAMapInFreemarker {}
  interface PageRespondToButtonClickWithObservable {}
  interface PageRigAMeshWithZspheresInZbrush {}
  interface PageSceneAndSequelPatternForWriters {}
  interface PageScriptForRotatingUnityGameObject90Degrees {}
  interface PageServeStaticResourcesWithSpringBoot {}
  interface PageSetThePageTitleInAngular {}
  interface PageShrinkWindowsVmOnVmwareFusionForMac {}
  interface PageSparqlExamplesAsk {}
  interface PageSparqlExamplesConstruct {}
  interface PageSparqlExamplesCountAllStatements {}
  interface PageSparqlExamplesDateRange {}
  interface PageSparqlExamplesFederation {}
  interface PageSparqlExamplesFilter {}
  interface PageSparqlExamplesInsert {}
  interface PageSparqlExamplesLimit {}
  interface PageSparqlExamplesListClasses {}
  interface PageSparqlExamplesNegation {}
  interface PageSparqlExamplesOrderBy {}
  interface PageSparqlExamplesPaging {}
  interface PageSparqlExamplesSelect {}
  interface PageStory {}
  interface PageTemplatePage {}
  interface PageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScripts {}
  interface PageUnityGetRigidbodyFromObject {}
  interface PageUnityPreferencesYourBuiltInKeyboardCheatSheet {}
  interface PageUnityRecipesFollowObject {}
  interface PageUnityRecipesHeadBobOrBreathe {}
  interface PageUnityRecipesLookTowardDirectionOfMovement {}
  interface PageUnityRecipesLookTowardDirectionOfVelocity {}
  interface PageUseAutoMaskingByPolygroupsInZbrush {}
  interface PageUseFibermeshInZbrush {}
  interface PageUseMicromeshInZbrush {}
  interface PageUsePrismJsInIonicStencilApp {}
  interface PageUseSpotlightToDisplayReferenceImagesInZbrush {}
  interface PageVietnam1967AmphibiousCombat {}
  interface PageWeldMultipleSubtoolsInZbrush {}
  interface PageXmlaccessSamples {}
  interface PageZbrushKeyboardShortcuts {}
  interface PageZbrushResourcesOnline {}
}

declare global {


  interface HTMLApp404PageNotFoundElement extends Components.App404PageNotFound, HTMLStencilElement {}
  var HTMLApp404PageNotFoundElement: {
    prototype: HTMLApp404PageNotFoundElement;
    new (): HTMLApp404PageNotFoundElement;
  };

  interface HTMLAppBlogFilterElement extends Components.AppBlogFilter, HTMLStencilElement {}
  var HTMLAppBlogFilterElement: {
    prototype: HTMLAppBlogFilterElement;
    new (): HTMLAppBlogFilterElement;
  };

  interface HTMLAppEntryMetaElement extends Components.AppEntryMeta, HTMLStencilElement {}
  var HTMLAppEntryMetaElement: {
    prototype: HTMLAppEntryMetaElement;
    new (): HTMLAppEntryMetaElement;
  };

  interface HTMLAppPhotoCardElement extends Components.AppPhotoCard, HTMLStencilElement {}
  var HTMLAppPhotoCardElement: {
    prototype: HTMLAppPhotoCardElement;
    new (): HTMLAppPhotoCardElement;
  };

  interface HTMLAppPhotosElement extends Components.AppPhotos, HTMLStencilElement {}
  var HTMLAppPhotosElement: {
    prototype: HTMLAppPhotosElement;
    new (): HTMLAppPhotosElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {}
  var HTMLAppTabsElement: {
    prototype: HTMLAppTabsElement;
    new (): HTMLAppTabsElement;
  };

  interface HTMLPage7QuintessentialBrushesForZbrushBeginnersElement extends Components.Page7QuintessentialBrushesForZbrushBeginners, HTMLStencilElement {}
  var HTMLPage7QuintessentialBrushesForZbrushBeginnersElement: {
    prototype: HTMLPage7QuintessentialBrushesForZbrushBeginnersElement;
    new (): HTMLPage7QuintessentialBrushesForZbrushBeginnersElement;
  };

  interface HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement extends Components.Page7ReasonsWhyTypescriptHelpsYouKickAss, HTMLStencilElement {}
  var HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement: {
    prototype: HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement;
    new (): HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement;
  };

  interface HTMLPageAJavascriptImplementationOfJavaUtilMapElement extends Components.PageAJavascriptImplementationOfJavaUtilMap, HTMLStencilElement {}
  var HTMLPageAJavascriptImplementationOfJavaUtilMapElement: {
    prototype: HTMLPageAJavascriptImplementationOfJavaUtilMapElement;
    new (): HTMLPageAJavascriptImplementationOfJavaUtilMapElement;
  };

  interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {}
  var HTMLPageAboutElement: {
    prototype: HTMLPageAboutElement;
    new (): HTMLPageAboutElement;
  };

  interface HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement extends Components.PageApplyDifferentMaterialsToSubtoolsInZbrush, HTMLStencilElement {}
  var HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement: {
    prototype: HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement;
    new (): HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement;
  };

  interface HTMLPageArtElement extends Components.PageArt, HTMLStencilElement {}
  var HTMLPageArtElement: {
    prototype: HTMLPageArtElement;
    new (): HTMLPageArtElement;
  };

  interface HTMLPageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnotherElement extends Components.PageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnother, HTMLStencilElement {}
  var HTMLPageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnotherElement: {
    prototype: HTMLPageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnotherElement;
    new (): HTMLPageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnotherElement;
  };

  interface HTMLPageBendThingsInZbrushWithTheBendCurveModifierElement extends Components.PageBendThingsInZbrushWithTheBendCurveModifier, HTMLStencilElement {}
  var HTMLPageBendThingsInZbrushWithTheBendCurveModifierElement: {
    prototype: HTMLPageBendThingsInZbrushWithTheBendCurveModifierElement;
    new (): HTMLPageBendThingsInZbrushWithTheBendCurveModifierElement;
  };

  interface HTMLPageBooksElement extends Components.PageBooks, HTMLStencilElement {}
  var HTMLPageBooksElement: {
    prototype: HTMLPageBooksElement;
    new (): HTMLPageBooksElement;
  };

  interface HTMLPageCageElement extends Components.PageCage, HTMLStencilElement {}
  var HTMLPageCageElement: {
    prototype: HTMLPageCageElement;
    new (): HTMLPageCageElement;
  };

  interface HTMLPageChangeCanvasBackgroundColorInZbrushElement extends Components.PageChangeCanvasBackgroundColorInZbrush, HTMLStencilElement {}
  var HTMLPageChangeCanvasBackgroundColorInZbrushElement: {
    prototype: HTMLPageChangeCanvasBackgroundColorInZbrushElement;
    new (): HTMLPageChangeCanvasBackgroundColorInZbrushElement;
  };

  interface HTMLPageCmdChronBeaverCageElement extends Components.PageCmdChronBeaverCage, HTMLStencilElement {}
  var HTMLPageCmdChronBeaverCageElement: {
    prototype: HTMLPageCmdChronBeaverCageElement;
    new (): HTMLPageCmdChronBeaverCageElement;
  };

  interface HTMLPageConfluencePanelMacroElement extends Components.PageConfluencePanelMacro, HTMLStencilElement {}
  var HTMLPageConfluencePanelMacroElement: {
    prototype: HTMLPageConfluencePanelMacroElement;
    new (): HTMLPageConfluencePanelMacroElement;
  };

  interface HTMLPageConvertZbrushPolygroupsIntoSubtoolsElement extends Components.PageConvertZbrushPolygroupsIntoSubtools, HTMLStencilElement {}
  var HTMLPageConvertZbrushPolygroupsIntoSubtoolsElement: {
    prototype: HTMLPageConvertZbrushPolygroupsIntoSubtoolsElement;
    new (): HTMLPageConvertZbrushPolygroupsIntoSubtoolsElement;
  };

  interface HTMLPageCopyAssetsFromNodeModulesInStencilJsElement extends Components.PageCopyAssetsFromNodeModulesInStencilJs, HTMLStencilElement {}
  var HTMLPageCopyAssetsFromNodeModulesInStencilJsElement: {
    prototype: HTMLPageCopyAssetsFromNodeModulesInStencilJsElement;
    new (): HTMLPageCopyAssetsFromNodeModulesInStencilJsElement;
  };

  interface HTMLPageCreateClothingInZbrushExtrudingMaskedAreaElement extends Components.PageCreateClothingInZbrushExtrudingMaskedArea, HTMLStencilElement {}
  var HTMLPageCreateClothingInZbrushExtrudingMaskedAreaElement: {
    prototype: HTMLPageCreateClothingInZbrushExtrudingMaskedAreaElement;
    new (): HTMLPageCreateClothingInZbrushExtrudingMaskedAreaElement;
  };

  interface HTMLPageCreateNewSubtoolFromMaskedAreaInZbrushElement extends Components.PageCreateNewSubtoolFromMaskedAreaInZbrush, HTMLStencilElement {}
  var HTMLPageCreateNewSubtoolFromMaskedAreaInZbrushElement: {
    prototype: HTMLPageCreateNewSubtoolFromMaskedAreaInZbrushElement;
    new (): HTMLPageCreateNewSubtoolFromMaskedAreaInZbrushElement;
  };

  interface HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart1Element extends Components.PageCreatePlayerHealthStatusIndicatorForUnityGuiPart1, HTMLStencilElement {}
  var HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart1Element: {
    prototype: HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart1Element;
    new (): HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart1Element;
  };

  interface HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart2Element extends Components.PageCreatePlayerHealthStatusIndicatorForUnityGuiPart2, HTMLStencilElement {}
  var HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart2Element: {
    prototype: HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart2Element;
    new (): HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart2Element;
  };

  interface HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart3Element extends Components.PageCreatePlayerHealthStatusIndicatorForUnityGuiPart3, HTMLStencilElement {}
  var HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart3Element: {
    prototype: HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart3Element;
    new (): HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart3Element;
  };

  interface HTMLPageCreatePolygroupFromMaskInZbrushElement extends Components.PageCreatePolygroupFromMaskInZbrush, HTMLStencilElement {}
  var HTMLPageCreatePolygroupFromMaskInZbrushElement: {
    prototype: HTMLPageCreatePolygroupFromMaskInZbrushElement;
    new (): HTMLPageCreatePolygroupFromMaskInZbrushElement;
  };

  interface HTMLPageDeleteHiddenGeometryInZbrushElement extends Components.PageDeleteHiddenGeometryInZbrush, HTMLStencilElement {}
  var HTMLPageDeleteHiddenGeometryInZbrushElement: {
    prototype: HTMLPageDeleteHiddenGeometryInZbrushElement;
    new (): HTMLPageDeleteHiddenGeometryInZbrushElement;
  };

  interface HTMLPageDockerCheatSheetElement extends Components.PageDockerCheatSheet, HTMLStencilElement {}
  var HTMLPageDockerCheatSheetElement: {
    prototype: HTMLPageDockerCheatSheetElement;
    new (): HTMLPageDockerCheatSheetElement;
  };

  interface HTMLPageFemaleAnatomyOutOfTheBoxInZbrushElement extends Components.PageFemaleAnatomyOutOfTheBoxInZbrush, HTMLStencilElement {}
  var HTMLPageFemaleAnatomyOutOfTheBoxInZbrushElement: {
    prototype: HTMLPageFemaleAnatomyOutOfTheBoxInZbrushElement;
    new (): HTMLPageFemaleAnatomyOutOfTheBoxInZbrushElement;
  };

  interface HTMLPageFindJavaClassesOrPackagesContainedInJarFilesElement extends Components.PageFindJavaClassesOrPackagesContainedInJarFiles, HTMLStencilElement {}
  var HTMLPageFindJavaClassesOrPackagesContainedInJarFilesElement: {
    prototype: HTMLPageFindJavaClassesOrPackagesContainedInJarFilesElement;
    new (): HTMLPageFindJavaClassesOrPackagesContainedInJarFilesElement;
  };

  interface HTMLPageFixForGitAfterMacosMojaveUpgradeElement extends Components.PageFixForGitAfterMacosMojaveUpgrade, HTMLStencilElement {}
  var HTMLPageFixForGitAfterMacosMojaveUpgradeElement: {
    prototype: HTMLPageFixForGitAfterMacosMojaveUpgradeElement;
    new (): HTMLPageFixForGitAfterMacosMojaveUpgradeElement;
  };

  interface HTMLPageFormatCurrencyInAngularElement extends Components.PageFormatCurrencyInAngular, HTMLStencilElement {}
  var HTMLPageFormatCurrencyInAngularElement: {
    prototype: HTMLPageFormatCurrencyInAngularElement;
    new (): HTMLPageFormatCurrencyInAngularElement;
  };

  interface HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement extends Components.PageGettingPartsOfAUrlFromTheHttpservletrequestObject, HTMLStencilElement {}
  var HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement: {
    prototype: HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement;
    new (): HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement;
  };

  interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {}
  var HTMLPageHomeElement: {
    prototype: HTMLPageHomeElement;
    new (): HTMLPageHomeElement;
  };

  interface HTMLPageHowToApplyTextureInZbrushElement extends Components.PageHowToApplyTextureInZbrush, HTMLStencilElement {}
  var HTMLPageHowToApplyTextureInZbrushElement: {
    prototype: HTMLPageHowToApplyTextureInZbrushElement;
    new (): HTMLPageHowToApplyTextureInZbrushElement;
  };

  interface HTMLPageHowToSketchWithZspheresInZbrushElement extends Components.PageHowToSketchWithZspheresInZbrush, HTMLStencilElement {}
  var HTMLPageHowToSketchWithZspheresInZbrushElement: {
    prototype: HTMLPageHowToSketchWithZspheresInZbrushElement;
    new (): HTMLPageHowToSketchWithZspheresInZbrushElement;
  };

  interface HTMLPageHowToUseLiveBooleanInZbrushElement extends Components.PageHowToUseLiveBooleanInZbrush, HTMLStencilElement {}
  var HTMLPageHowToUseLiveBooleanInZbrushElement: {
    prototype: HTMLPageHowToUseLiveBooleanInZbrushElement;
    new (): HTMLPageHowToUseLiveBooleanInZbrushElement;
  };

  interface HTMLPageIndexOfItemWithinAngularNgforLoopElement extends Components.PageIndexOfItemWithinAngularNgforLoop, HTMLStencilElement {}
  var HTMLPageIndexOfItemWithinAngularNgforLoopElement: {
    prototype: HTMLPageIndexOfItemWithinAngularNgforLoopElement;
    new (): HTMLPageIndexOfItemWithinAngularNgforLoopElement;
  };

  interface HTMLPageInstallJavaPluginFor64bitFirefoxOnCentos64Element extends Components.PageInstallJavaPluginFor64bitFirefoxOnCentos64, HTMLStencilElement {}
  var HTMLPageInstallJavaPluginFor64bitFirefoxOnCentos64Element: {
    prototype: HTMLPageInstallJavaPluginFor64bitFirefoxOnCentos64Element;
    new (): HTMLPageInstallJavaPluginFor64bitFirefoxOnCentos64Element;
  };

  interface HTMLPageInstallOracleJava8OnUbuntuElement extends Components.PageInstallOracleJava8OnUbuntu, HTMLStencilElement {}
  var HTMLPageInstallOracleJava8OnUbuntuElement: {
    prototype: HTMLPageInstallOracleJava8OnUbuntuElement;
    new (): HTMLPageInstallOracleJava8OnUbuntuElement;
  };

  interface HTMLPageIsolateAPolygroupInZbrushElement extends Components.PageIsolateAPolygroupInZbrush, HTMLStencilElement {}
  var HTMLPageIsolateAPolygroupInZbrushElement: {
    prototype: HTMLPageIsolateAPolygroupInZbrushElement;
    new (): HTMLPageIsolateAPolygroupInZbrushElement;
  };

  interface HTMLPageKillingKittensElement extends Components.PageKillingKittens, HTMLStencilElement {}
  var HTMLPageKillingKittensElement: {
    prototype: HTMLPageKillingKittensElement;
    new (): HTMLPageKillingKittensElement;
  };

  interface HTMLPageLifeEventsElement extends Components.PageLifeEvents, HTMLStencilElement {}
  var HTMLPageLifeEventsElement: {
    prototype: HTMLPageLifeEventsElement;
    new (): HTMLPageLifeEventsElement;
  };

  interface HTMLPageListIbmDb2CommandsElement extends Components.PageListIbmDb2Commands, HTMLStencilElement {}
  var HTMLPageListIbmDb2CommandsElement: {
    prototype: HTMLPageListIbmDb2CommandsElement;
    new (): HTMLPageListIbmDb2CommandsElement;
  };

  interface HTMLPageLoggingWithSpringBootElement extends Components.PageLoggingWithSpringBoot, HTMLStencilElement {}
  var HTMLPageLoggingWithSpringBootElement: {
    prototype: HTMLPageLoggingWithSpringBootElement;
    new (): HTMLPageLoggingWithSpringBootElement;
  };

  interface HTMLPageMakeAZbrushSpeedSculptTimelapseVideoElement extends Components.PageMakeAZbrushSpeedSculptTimelapseVideo, HTMLStencilElement {}
  var HTMLPageMakeAZbrushSpeedSculptTimelapseVideoElement: {
    prototype: HTMLPageMakeAZbrushSpeedSculptTimelapseVideoElement;
    new (): HTMLPageMakeAZbrushSpeedSculptTimelapseVideoElement;
  };

  interface HTMLPageMappingToAViewInSpringWhenNoControllerLogicIsRequiredElement extends Components.PageMappingToAViewInSpringWhenNoControllerLogicIsRequired, HTMLStencilElement {}
  var HTMLPageMappingToAViewInSpringWhenNoControllerLogicIsRequiredElement: {
    prototype: HTMLPageMappingToAViewInSpringWhenNoControllerLogicIsRequiredElement;
    new (): HTMLPageMappingToAViewInSpringWhenNoControllerLogicIsRequiredElement;
  };

  interface HTMLPageMirrorPolygroupOnSubtoolInZbrushElement extends Components.PageMirrorPolygroupOnSubtoolInZbrush, HTMLStencilElement {}
  var HTMLPageMirrorPolygroupOnSubtoolInZbrushElement: {
    prototype: HTMLPageMirrorPolygroupOnSubtoolInZbrushElement;
    new (): HTMLPageMirrorPolygroupOnSubtoolInZbrushElement;
  };

  interface HTMLPagePhotosWeaponsPlatoonElement extends Components.PagePhotosWeaponsPlatoon, HTMLStencilElement {}
  var HTMLPagePhotosWeaponsPlatoonElement: {
    prototype: HTMLPagePhotosWeaponsPlatoonElement;
    new (): HTMLPagePhotosWeaponsPlatoonElement;
  };

  interface HTMLPagePinkHeartsElement extends Components.PagePinkHearts, HTMLStencilElement {}
  var HTMLPagePinkHeartsElement: {
    prototype: HTMLPagePinkHeartsElement;
    new (): HTMLPagePinkHeartsElement;
  };

  interface HTMLPagePwaWithIonicAngularWordpressApi1Element extends Components.PagePwaWithIonicAngularWordpressApi1, HTMLStencilElement {}
  var HTMLPagePwaWithIonicAngularWordpressApi1Element: {
    prototype: HTMLPagePwaWithIonicAngularWordpressApi1Element;
    new (): HTMLPagePwaWithIonicAngularWordpressApi1Element;
  };

  interface HTMLPagePwaWithIonicAngularWordpressApi2Element extends Components.PagePwaWithIonicAngularWordpressApi2, HTMLStencilElement {}
  var HTMLPagePwaWithIonicAngularWordpressApi2Element: {
    prototype: HTMLPagePwaWithIonicAngularWordpressApi2Element;
    new (): HTMLPagePwaWithIonicAngularWordpressApi2Element;
  };

  interface HTMLPagePwaWithIonicAngularWordpressApi3Element extends Components.PagePwaWithIonicAngularWordpressApi3, HTMLStencilElement {}
  var HTMLPagePwaWithIonicAngularWordpressApi3Element: {
    prototype: HTMLPagePwaWithIonicAngularWordpressApi3Element;
    new (): HTMLPagePwaWithIonicAngularWordpressApi3Element;
  };

  interface HTMLPagePwaWithIonicAngularWordpressApi4Element extends Components.PagePwaWithIonicAngularWordpressApi4, HTMLStencilElement {}
  var HTMLPagePwaWithIonicAngularWordpressApi4Element: {
    prototype: HTMLPagePwaWithIonicAngularWordpressApi4Element;
    new (): HTMLPagePwaWithIonicAngularWordpressApi4Element;
  };

  interface HTMLPagePwaWithIonicAngularWordpressApi5Element extends Components.PagePwaWithIonicAngularWordpressApi5, HTMLStencilElement {}
  var HTMLPagePwaWithIonicAngularWordpressApi5Element: {
    prototype: HTMLPagePwaWithIonicAngularWordpressApi5Element;
    new (): HTMLPagePwaWithIonicAngularWordpressApi5Element;
  };

  interface HTMLPageQuickAndSimpleCachingWithApacheCommonsJcsElement extends Components.PageQuickAndSimpleCachingWithApacheCommonsJcs, HTMLStencilElement {}
  var HTMLPageQuickAndSimpleCachingWithApacheCommonsJcsElement: {
    prototype: HTMLPageQuickAndSimpleCachingWithApacheCommonsJcsElement;
    new (): HTMLPageQuickAndSimpleCachingWithApacheCommonsJcsElement;
  };

  interface HTMLPageRayKelleySilverStarElement extends Components.PageRayKelleySilverStar, HTMLStencilElement {}
  var HTMLPageRayKelleySilverStarElement: {
    prototype: HTMLPageRayKelleySilverStarElement;
    new (): HTMLPageRayKelleySilverStarElement;
  };

  interface HTMLPageRdfSyntaxExamplesElement extends Components.PageRdfSyntaxExamples, HTMLStencilElement {}
  var HTMLPageRdfSyntaxExamplesElement: {
    prototype: HTMLPageRdfSyntaxExamplesElement;
    new (): HTMLPageRdfSyntaxExamplesElement;
  };

  interface HTMLPageRenderTheKeysAndValuesFromAMapInFreemarkerElement extends Components.PageRenderTheKeysAndValuesFromAMapInFreemarker, HTMLStencilElement {}
  var HTMLPageRenderTheKeysAndValuesFromAMapInFreemarkerElement: {
    prototype: HTMLPageRenderTheKeysAndValuesFromAMapInFreemarkerElement;
    new (): HTMLPageRenderTheKeysAndValuesFromAMapInFreemarkerElement;
  };

  interface HTMLPageRespondToButtonClickWithObservableElement extends Components.PageRespondToButtonClickWithObservable, HTMLStencilElement {}
  var HTMLPageRespondToButtonClickWithObservableElement: {
    prototype: HTMLPageRespondToButtonClickWithObservableElement;
    new (): HTMLPageRespondToButtonClickWithObservableElement;
  };

  interface HTMLPageRigAMeshWithZspheresInZbrushElement extends Components.PageRigAMeshWithZspheresInZbrush, HTMLStencilElement {}
  var HTMLPageRigAMeshWithZspheresInZbrushElement: {
    prototype: HTMLPageRigAMeshWithZspheresInZbrushElement;
    new (): HTMLPageRigAMeshWithZspheresInZbrushElement;
  };

  interface HTMLPageSceneAndSequelPatternForWritersElement extends Components.PageSceneAndSequelPatternForWriters, HTMLStencilElement {}
  var HTMLPageSceneAndSequelPatternForWritersElement: {
    prototype: HTMLPageSceneAndSequelPatternForWritersElement;
    new (): HTMLPageSceneAndSequelPatternForWritersElement;
  };

  interface HTMLPageScriptForRotatingUnityGameObject90DegreesElement extends Components.PageScriptForRotatingUnityGameObject90Degrees, HTMLStencilElement {}
  var HTMLPageScriptForRotatingUnityGameObject90DegreesElement: {
    prototype: HTMLPageScriptForRotatingUnityGameObject90DegreesElement;
    new (): HTMLPageScriptForRotatingUnityGameObject90DegreesElement;
  };

  interface HTMLPageServeStaticResourcesWithSpringBootElement extends Components.PageServeStaticResourcesWithSpringBoot, HTMLStencilElement {}
  var HTMLPageServeStaticResourcesWithSpringBootElement: {
    prototype: HTMLPageServeStaticResourcesWithSpringBootElement;
    new (): HTMLPageServeStaticResourcesWithSpringBootElement;
  };

  interface HTMLPageSetThePageTitleInAngularElement extends Components.PageSetThePageTitleInAngular, HTMLStencilElement {}
  var HTMLPageSetThePageTitleInAngularElement: {
    prototype: HTMLPageSetThePageTitleInAngularElement;
    new (): HTMLPageSetThePageTitleInAngularElement;
  };

  interface HTMLPageShrinkWindowsVmOnVmwareFusionForMacElement extends Components.PageShrinkWindowsVmOnVmwareFusionForMac, HTMLStencilElement {}
  var HTMLPageShrinkWindowsVmOnVmwareFusionForMacElement: {
    prototype: HTMLPageShrinkWindowsVmOnVmwareFusionForMacElement;
    new (): HTMLPageShrinkWindowsVmOnVmwareFusionForMacElement;
  };

  interface HTMLPageSparqlExamplesAskElement extends Components.PageSparqlExamplesAsk, HTMLStencilElement {}
  var HTMLPageSparqlExamplesAskElement: {
    prototype: HTMLPageSparqlExamplesAskElement;
    new (): HTMLPageSparqlExamplesAskElement;
  };

  interface HTMLPageSparqlExamplesConstructElement extends Components.PageSparqlExamplesConstruct, HTMLStencilElement {}
  var HTMLPageSparqlExamplesConstructElement: {
    prototype: HTMLPageSparqlExamplesConstructElement;
    new (): HTMLPageSparqlExamplesConstructElement;
  };

  interface HTMLPageSparqlExamplesCountAllStatementsElement extends Components.PageSparqlExamplesCountAllStatements, HTMLStencilElement {}
  var HTMLPageSparqlExamplesCountAllStatementsElement: {
    prototype: HTMLPageSparqlExamplesCountAllStatementsElement;
    new (): HTMLPageSparqlExamplesCountAllStatementsElement;
  };

  interface HTMLPageSparqlExamplesDateRangeElement extends Components.PageSparqlExamplesDateRange, HTMLStencilElement {}
  var HTMLPageSparqlExamplesDateRangeElement: {
    prototype: HTMLPageSparqlExamplesDateRangeElement;
    new (): HTMLPageSparqlExamplesDateRangeElement;
  };

  interface HTMLPageSparqlExamplesFederationElement extends Components.PageSparqlExamplesFederation, HTMLStencilElement {}
  var HTMLPageSparqlExamplesFederationElement: {
    prototype: HTMLPageSparqlExamplesFederationElement;
    new (): HTMLPageSparqlExamplesFederationElement;
  };

  interface HTMLPageSparqlExamplesFilterElement extends Components.PageSparqlExamplesFilter, HTMLStencilElement {}
  var HTMLPageSparqlExamplesFilterElement: {
    prototype: HTMLPageSparqlExamplesFilterElement;
    new (): HTMLPageSparqlExamplesFilterElement;
  };

  interface HTMLPageSparqlExamplesInsertElement extends Components.PageSparqlExamplesInsert, HTMLStencilElement {}
  var HTMLPageSparqlExamplesInsertElement: {
    prototype: HTMLPageSparqlExamplesInsertElement;
    new (): HTMLPageSparqlExamplesInsertElement;
  };

  interface HTMLPageSparqlExamplesLimitElement extends Components.PageSparqlExamplesLimit, HTMLStencilElement {}
  var HTMLPageSparqlExamplesLimitElement: {
    prototype: HTMLPageSparqlExamplesLimitElement;
    new (): HTMLPageSparqlExamplesLimitElement;
  };

  interface HTMLPageSparqlExamplesListClassesElement extends Components.PageSparqlExamplesListClasses, HTMLStencilElement {}
  var HTMLPageSparqlExamplesListClassesElement: {
    prototype: HTMLPageSparqlExamplesListClassesElement;
    new (): HTMLPageSparqlExamplesListClassesElement;
  };

  interface HTMLPageSparqlExamplesNegationElement extends Components.PageSparqlExamplesNegation, HTMLStencilElement {}
  var HTMLPageSparqlExamplesNegationElement: {
    prototype: HTMLPageSparqlExamplesNegationElement;
    new (): HTMLPageSparqlExamplesNegationElement;
  };

  interface HTMLPageSparqlExamplesOrderByElement extends Components.PageSparqlExamplesOrderBy, HTMLStencilElement {}
  var HTMLPageSparqlExamplesOrderByElement: {
    prototype: HTMLPageSparqlExamplesOrderByElement;
    new (): HTMLPageSparqlExamplesOrderByElement;
  };

  interface HTMLPageSparqlExamplesPagingElement extends Components.PageSparqlExamplesPaging, HTMLStencilElement {}
  var HTMLPageSparqlExamplesPagingElement: {
    prototype: HTMLPageSparqlExamplesPagingElement;
    new (): HTMLPageSparqlExamplesPagingElement;
  };

  interface HTMLPageSparqlExamplesSelectElement extends Components.PageSparqlExamplesSelect, HTMLStencilElement {}
  var HTMLPageSparqlExamplesSelectElement: {
    prototype: HTMLPageSparqlExamplesSelectElement;
    new (): HTMLPageSparqlExamplesSelectElement;
  };

  interface HTMLPageStoryElement extends Components.PageStory, HTMLStencilElement {}
  var HTMLPageStoryElement: {
    prototype: HTMLPageStoryElement;
    new (): HTMLPageStoryElement;
  };

  interface HTMLPageTemplatePageElement extends Components.PageTemplatePage, HTMLStencilElement {}
  var HTMLPageTemplatePageElement: {
    prototype: HTMLPageTemplatePageElement;
    new (): HTMLPageTemplatePageElement;
  };

  interface HTMLPageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScriptsElement extends Components.PageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScripts, HTMLStencilElement {}
  var HTMLPageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScriptsElement: {
    prototype: HTMLPageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScriptsElement;
    new (): HTMLPageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScriptsElement;
  };

  interface HTMLPageUnityGetRigidbodyFromObjectElement extends Components.PageUnityGetRigidbodyFromObject, HTMLStencilElement {}
  var HTMLPageUnityGetRigidbodyFromObjectElement: {
    prototype: HTMLPageUnityGetRigidbodyFromObjectElement;
    new (): HTMLPageUnityGetRigidbodyFromObjectElement;
  };

  interface HTMLPageUnityPreferencesYourBuiltInKeyboardCheatSheetElement extends Components.PageUnityPreferencesYourBuiltInKeyboardCheatSheet, HTMLStencilElement {}
  var HTMLPageUnityPreferencesYourBuiltInKeyboardCheatSheetElement: {
    prototype: HTMLPageUnityPreferencesYourBuiltInKeyboardCheatSheetElement;
    new (): HTMLPageUnityPreferencesYourBuiltInKeyboardCheatSheetElement;
  };

  interface HTMLPageUnityRecipesFollowObjectElement extends Components.PageUnityRecipesFollowObject, HTMLStencilElement {}
  var HTMLPageUnityRecipesFollowObjectElement: {
    prototype: HTMLPageUnityRecipesFollowObjectElement;
    new (): HTMLPageUnityRecipesFollowObjectElement;
  };

  interface HTMLPageUnityRecipesHeadBobOrBreatheElement extends Components.PageUnityRecipesHeadBobOrBreathe, HTMLStencilElement {}
  var HTMLPageUnityRecipesHeadBobOrBreatheElement: {
    prototype: HTMLPageUnityRecipesHeadBobOrBreatheElement;
    new (): HTMLPageUnityRecipesHeadBobOrBreatheElement;
  };

  interface HTMLPageUnityRecipesLookTowardDirectionOfMovementElement extends Components.PageUnityRecipesLookTowardDirectionOfMovement, HTMLStencilElement {}
  var HTMLPageUnityRecipesLookTowardDirectionOfMovementElement: {
    prototype: HTMLPageUnityRecipesLookTowardDirectionOfMovementElement;
    new (): HTMLPageUnityRecipesLookTowardDirectionOfMovementElement;
  };

  interface HTMLPageUnityRecipesLookTowardDirectionOfVelocityElement extends Components.PageUnityRecipesLookTowardDirectionOfVelocity, HTMLStencilElement {}
  var HTMLPageUnityRecipesLookTowardDirectionOfVelocityElement: {
    prototype: HTMLPageUnityRecipesLookTowardDirectionOfVelocityElement;
    new (): HTMLPageUnityRecipesLookTowardDirectionOfVelocityElement;
  };

  interface HTMLPageUseAutoMaskingByPolygroupsInZbrushElement extends Components.PageUseAutoMaskingByPolygroupsInZbrush, HTMLStencilElement {}
  var HTMLPageUseAutoMaskingByPolygroupsInZbrushElement: {
    prototype: HTMLPageUseAutoMaskingByPolygroupsInZbrushElement;
    new (): HTMLPageUseAutoMaskingByPolygroupsInZbrushElement;
  };

  interface HTMLPageUseFibermeshInZbrushElement extends Components.PageUseFibermeshInZbrush, HTMLStencilElement {}
  var HTMLPageUseFibermeshInZbrushElement: {
    prototype: HTMLPageUseFibermeshInZbrushElement;
    new (): HTMLPageUseFibermeshInZbrushElement;
  };

  interface HTMLPageUseMicromeshInZbrushElement extends Components.PageUseMicromeshInZbrush, HTMLStencilElement {}
  var HTMLPageUseMicromeshInZbrushElement: {
    prototype: HTMLPageUseMicromeshInZbrushElement;
    new (): HTMLPageUseMicromeshInZbrushElement;
  };

  interface HTMLPageUsePrismJsInIonicStencilAppElement extends Components.PageUsePrismJsInIonicStencilApp, HTMLStencilElement {}
  var HTMLPageUsePrismJsInIonicStencilAppElement: {
    prototype: HTMLPageUsePrismJsInIonicStencilAppElement;
    new (): HTMLPageUsePrismJsInIonicStencilAppElement;
  };

  interface HTMLPageUseSpotlightToDisplayReferenceImagesInZbrushElement extends Components.PageUseSpotlightToDisplayReferenceImagesInZbrush, HTMLStencilElement {}
  var HTMLPageUseSpotlightToDisplayReferenceImagesInZbrushElement: {
    prototype: HTMLPageUseSpotlightToDisplayReferenceImagesInZbrushElement;
    new (): HTMLPageUseSpotlightToDisplayReferenceImagesInZbrushElement;
  };

  interface HTMLPageVietnam1967AmphibiousCombatElement extends Components.PageVietnam1967AmphibiousCombat, HTMLStencilElement {}
  var HTMLPageVietnam1967AmphibiousCombatElement: {
    prototype: HTMLPageVietnam1967AmphibiousCombatElement;
    new (): HTMLPageVietnam1967AmphibiousCombatElement;
  };

  interface HTMLPageWeldMultipleSubtoolsInZbrushElement extends Components.PageWeldMultipleSubtoolsInZbrush, HTMLStencilElement {}
  var HTMLPageWeldMultipleSubtoolsInZbrushElement: {
    prototype: HTMLPageWeldMultipleSubtoolsInZbrushElement;
    new (): HTMLPageWeldMultipleSubtoolsInZbrushElement;
  };

  interface HTMLPageXmlaccessSamplesElement extends Components.PageXmlaccessSamples, HTMLStencilElement {}
  var HTMLPageXmlaccessSamplesElement: {
    prototype: HTMLPageXmlaccessSamplesElement;
    new (): HTMLPageXmlaccessSamplesElement;
  };

  interface HTMLPageZbrushKeyboardShortcutsElement extends Components.PageZbrushKeyboardShortcuts, HTMLStencilElement {}
  var HTMLPageZbrushKeyboardShortcutsElement: {
    prototype: HTMLPageZbrushKeyboardShortcutsElement;
    new (): HTMLPageZbrushKeyboardShortcutsElement;
  };

  interface HTMLPageZbrushResourcesOnlineElement extends Components.PageZbrushResourcesOnline, HTMLStencilElement {}
  var HTMLPageZbrushResourcesOnlineElement: {
    prototype: HTMLPageZbrushResourcesOnlineElement;
    new (): HTMLPageZbrushResourcesOnlineElement;
  };
  interface HTMLElementTagNameMap {
    'app-404-page-not-found': HTMLApp404PageNotFoundElement;
    'app-blog-filter': HTMLAppBlogFilterElement;
    'app-entry-meta': HTMLAppEntryMetaElement;
    'app-photo-card': HTMLAppPhotoCardElement;
    'app-photos': HTMLAppPhotosElement;
    'app-root': HTMLAppRootElement;
    'app-tabs': HTMLAppTabsElement;
    'page-7-quintessential-brushes-for-zbrush-beginners': HTMLPage7QuintessentialBrushesForZbrushBeginnersElement;
    'page-7-reasons-why-typescript-helps-you-kick-ass': HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement;
    'page-a-javascript-implementation-of-java-util-map': HTMLPageAJavascriptImplementationOfJavaUtilMapElement;
    'page-about': HTMLPageAboutElement;
    'page-apply-different-materials-to-subtools-in-zbrush': HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement;
    'page-art': HTMLPageArtElement;
    'page-automatically-build-and-include-one-eclipse-project-into-another': HTMLPageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnotherElement;
    'page-bend-things-in-zbrush-with-the-bend-curve-modifier': HTMLPageBendThingsInZbrushWithTheBendCurveModifierElement;
    'page-books': HTMLPageBooksElement;
    'page-cage': HTMLPageCageElement;
    'page-change-canvas-background-color-in-zbrush': HTMLPageChangeCanvasBackgroundColorInZbrushElement;
    'page-cmd-chron-beaver-cage': HTMLPageCmdChronBeaverCageElement;
    'page-confluence-panel-macro': HTMLPageConfluencePanelMacroElement;
    'page-convert-zbrush-polygroups-into-subtools': HTMLPageConvertZbrushPolygroupsIntoSubtoolsElement;
    'page-copy-assets-from-node-modules-in-stencil-js': HTMLPageCopyAssetsFromNodeModulesInStencilJsElement;
    'page-create-clothing-in-zbrush-extruding-masked-area': HTMLPageCreateClothingInZbrushExtrudingMaskedAreaElement;
    'page-create-new-subtool-from-masked-area-in-zbrush': HTMLPageCreateNewSubtoolFromMaskedAreaInZbrushElement;
    'page-create-player-health-status-indicator-for-unity-gui-part-1': HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart1Element;
    'page-create-player-health-status-indicator-for-unity-gui-part-2': HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart2Element;
    'page-create-player-health-status-indicator-for-unity-gui-part-3': HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart3Element;
    'page-create-polygroup-from-mask-in-zbrush': HTMLPageCreatePolygroupFromMaskInZbrushElement;
    'page-delete-hidden-geometry-in-zbrush': HTMLPageDeleteHiddenGeometryInZbrushElement;
    'page-docker-cheat-sheet': HTMLPageDockerCheatSheetElement;
    'page-female-anatomy-out-of-the-box-in-zbrush': HTMLPageFemaleAnatomyOutOfTheBoxInZbrushElement;
    'page-find-java-classes-or-packages-contained-in-jar-files': HTMLPageFindJavaClassesOrPackagesContainedInJarFilesElement;
    'page-fix-for-git-after-macos-mojave-upgrade': HTMLPageFixForGitAfterMacosMojaveUpgradeElement;
    'page-format-currency-in-angular': HTMLPageFormatCurrencyInAngularElement;
    'page-getting-parts-of-a-url-from-the-httpservletrequest-object': HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement;
    'page-home': HTMLPageHomeElement;
    'page-how-to-apply-texture-in-zbrush': HTMLPageHowToApplyTextureInZbrushElement;
    'page-how-to-sketch-with-zspheres-in-zbrush': HTMLPageHowToSketchWithZspheresInZbrushElement;
    'page-how-to-use-live-boolean-in-zbrush': HTMLPageHowToUseLiveBooleanInZbrushElement;
    'page-index-of-item-within-angular-ngfor-loop': HTMLPageIndexOfItemWithinAngularNgforLoopElement;
    'page-install-java-plugin-for-64bit-firefox-on-centos-6-4': HTMLPageInstallJavaPluginFor64bitFirefoxOnCentos64Element;
    'page-install-oracle-java-8-on-ubuntu': HTMLPageInstallOracleJava8OnUbuntuElement;
    'page-isolate-a-polygroup-in-zbrush': HTMLPageIsolateAPolygroupInZbrushElement;
    'page-killing-kittens': HTMLPageKillingKittensElement;
    'page-life-events': HTMLPageLifeEventsElement;
    'page-list-ibm-db2-commands': HTMLPageListIbmDb2CommandsElement;
    'page-logging-with-spring-boot': HTMLPageLoggingWithSpringBootElement;
    'page-make-a-zbrush-speed-sculpt-timelapse-video': HTMLPageMakeAZbrushSpeedSculptTimelapseVideoElement;
    'page-mapping-to-a-view-in-spring-when-no-controller-logic-is-required': HTMLPageMappingToAViewInSpringWhenNoControllerLogicIsRequiredElement;
    'page-mirror-polygroup-on-subtool-in-zbrush': HTMLPageMirrorPolygroupOnSubtoolInZbrushElement;
    'page-photos-weapons-platoon': HTMLPagePhotosWeaponsPlatoonElement;
    'page-pink-hearts': HTMLPagePinkHeartsElement;
    'page-pwa-with-ionic-angular-wordpress-api-1': HTMLPagePwaWithIonicAngularWordpressApi1Element;
    'page-pwa-with-ionic-angular-wordpress-api-2': HTMLPagePwaWithIonicAngularWordpressApi2Element;
    'page-pwa-with-ionic-angular-wordpress-api-3': HTMLPagePwaWithIonicAngularWordpressApi3Element;
    'page-pwa-with-ionic-angular-wordpress-api-4': HTMLPagePwaWithIonicAngularWordpressApi4Element;
    'page-pwa-with-ionic-angular-wordpress-api-5': HTMLPagePwaWithIonicAngularWordpressApi5Element;
    'page-quick-and-simple-caching-with-apache-commons-jcs': HTMLPageQuickAndSimpleCachingWithApacheCommonsJcsElement;
    'page-ray-kelley-silver-star': HTMLPageRayKelleySilverStarElement;
    'page-rdf-syntax-examples': HTMLPageRdfSyntaxExamplesElement;
    'page-render-the-keys-and-values-from-a-map-in-freemarker': HTMLPageRenderTheKeysAndValuesFromAMapInFreemarkerElement;
    'page-respond-to-button-click-with-observable': HTMLPageRespondToButtonClickWithObservableElement;
    'page-rig-a-mesh-with-zspheres-in-zbrush': HTMLPageRigAMeshWithZspheresInZbrushElement;
    'page-scene-and-sequel-pattern-for-writers': HTMLPageSceneAndSequelPatternForWritersElement;
    'page-script-for-rotating-unity-game-object-90-degrees': HTMLPageScriptForRotatingUnityGameObject90DegreesElement;
    'page-serve-static-resources-with-spring-boot': HTMLPageServeStaticResourcesWithSpringBootElement;
    'page-set-the-page-title-in-angular': HTMLPageSetThePageTitleInAngularElement;
    'page-shrink-windows-vm-on-vmware-fusion-for-mac': HTMLPageShrinkWindowsVmOnVmwareFusionForMacElement;
    'page-sparql-examples-ask': HTMLPageSparqlExamplesAskElement;
    'page-sparql-examples-construct': HTMLPageSparqlExamplesConstructElement;
    'page-sparql-examples-count-all-statements': HTMLPageSparqlExamplesCountAllStatementsElement;
    'page-sparql-examples-date-range': HTMLPageSparqlExamplesDateRangeElement;
    'page-sparql-examples-federation': HTMLPageSparqlExamplesFederationElement;
    'page-sparql-examples-filter': HTMLPageSparqlExamplesFilterElement;
    'page-sparql-examples-insert': HTMLPageSparqlExamplesInsertElement;
    'page-sparql-examples-limit': HTMLPageSparqlExamplesLimitElement;
    'page-sparql-examples-list-classes': HTMLPageSparqlExamplesListClassesElement;
    'page-sparql-examples-negation': HTMLPageSparqlExamplesNegationElement;
    'page-sparql-examples-order-by': HTMLPageSparqlExamplesOrderByElement;
    'page-sparql-examples-paging': HTMLPageSparqlExamplesPagingElement;
    'page-sparql-examples-select': HTMLPageSparqlExamplesSelectElement;
    'page-story': HTMLPageStoryElement;
    'page-template-page': HTMLPageTemplatePageElement;
    'page-unity-freebies-game-timer-cinematic-letterbox-and-fade-in-scripts': HTMLPageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScriptsElement;
    'page-unity-get-rigidbody-from-object': HTMLPageUnityGetRigidbodyFromObjectElement;
    'page-unity-preferences-your-built-in-keyboard-cheat-sheet': HTMLPageUnityPreferencesYourBuiltInKeyboardCheatSheetElement;
    'page-unity-recipes-follow-object': HTMLPageUnityRecipesFollowObjectElement;
    'page-unity-recipes-head-bob-or-breathe': HTMLPageUnityRecipesHeadBobOrBreatheElement;
    'page-unity-recipes-look-toward-direction-of-movement': HTMLPageUnityRecipesLookTowardDirectionOfMovementElement;
    'page-unity-recipes-look-toward-direction-of-velocity': HTMLPageUnityRecipesLookTowardDirectionOfVelocityElement;
    'page-use-auto-masking-by-polygroups-in-zbrush': HTMLPageUseAutoMaskingByPolygroupsInZbrushElement;
    'page-use-fibermesh-in-zbrush': HTMLPageUseFibermeshInZbrushElement;
    'page-use-micromesh-in-zbrush': HTMLPageUseMicromeshInZbrushElement;
    'page-use-prism-js-in-ionic-stencil-app': HTMLPageUsePrismJsInIonicStencilAppElement;
    'page-use-spotlight-to-display-reference-images-in-zbrush': HTMLPageUseSpotlightToDisplayReferenceImagesInZbrushElement;
    'page-vietnam-1967-amphibious-combat': HTMLPageVietnam1967AmphibiousCombatElement;
    'page-weld-multiple-subtools-in-zbrush': HTMLPageWeldMultipleSubtoolsInZbrushElement;
    'page-xmlaccess-samples': HTMLPageXmlaccessSamplesElement;
    'page-zbrush-keyboard-shortcuts': HTMLPageZbrushKeyboardShortcutsElement;
    'page-zbrush-resources-online': HTMLPageZbrushResourcesOnlineElement;
  }
}

declare namespace LocalJSX {
  interface App404PageNotFound {}
  interface AppBlogFilter {
    'excludedTracks'?: string[];
  }
  interface AppEntryMeta {
    'header'?: any;
  }
  interface AppPhotoCard {
    'imagePath'?: string;
    'item'?: any;
  }
  interface AppPhotos {
    'name'?: string;
  }
  interface AppRoot {}
  interface AppTabs {}
  interface Page7QuintessentialBrushesForZbrushBeginners {}
  interface Page7ReasonsWhyTypescriptHelpsYouKickAss {}
  interface PageAJavascriptImplementationOfJavaUtilMap {}
  interface PageAbout {}
  interface PageApplyDifferentMaterialsToSubtoolsInZbrush {}
  interface PageArt {}
  interface PageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnother {}
  interface PageBendThingsInZbrushWithTheBendCurveModifier {}
  interface PageBooks {}
  interface PageCage {}
  interface PageChangeCanvasBackgroundColorInZbrush {}
  interface PageCmdChronBeaverCage {}
  interface PageConfluencePanelMacro {}
  interface PageConvertZbrushPolygroupsIntoSubtools {}
  interface PageCopyAssetsFromNodeModulesInStencilJs {}
  interface PageCreateClothingInZbrushExtrudingMaskedArea {}
  interface PageCreateNewSubtoolFromMaskedAreaInZbrush {}
  interface PageCreatePlayerHealthStatusIndicatorForUnityGuiPart1 {}
  interface PageCreatePlayerHealthStatusIndicatorForUnityGuiPart2 {}
  interface PageCreatePlayerHealthStatusIndicatorForUnityGuiPart3 {}
  interface PageCreatePolygroupFromMaskInZbrush {}
  interface PageDeleteHiddenGeometryInZbrush {}
  interface PageDockerCheatSheet {}
  interface PageFemaleAnatomyOutOfTheBoxInZbrush {}
  interface PageFindJavaClassesOrPackagesContainedInJarFiles {}
  interface PageFixForGitAfterMacosMojaveUpgrade {}
  interface PageFormatCurrencyInAngular {}
  interface PageGettingPartsOfAUrlFromTheHttpservletrequestObject {}
  interface PageHome {}
  interface PageHowToApplyTextureInZbrush {}
  interface PageHowToSketchWithZspheresInZbrush {}
  interface PageHowToUseLiveBooleanInZbrush {}
  interface PageIndexOfItemWithinAngularNgforLoop {}
  interface PageInstallJavaPluginFor64bitFirefoxOnCentos64 {}
  interface PageInstallOracleJava8OnUbuntu {}
  interface PageIsolateAPolygroupInZbrush {}
  interface PageKillingKittens {}
  interface PageLifeEvents {}
  interface PageListIbmDb2Commands {}
  interface PageLoggingWithSpringBoot {}
  interface PageMakeAZbrushSpeedSculptTimelapseVideo {}
  interface PageMappingToAViewInSpringWhenNoControllerLogicIsRequired {}
  interface PageMirrorPolygroupOnSubtoolInZbrush {}
  interface PagePhotosWeaponsPlatoon {}
  interface PagePinkHearts {}
  interface PagePwaWithIonicAngularWordpressApi1 {}
  interface PagePwaWithIonicAngularWordpressApi2 {}
  interface PagePwaWithIonicAngularWordpressApi3 {}
  interface PagePwaWithIonicAngularWordpressApi4 {}
  interface PagePwaWithIonicAngularWordpressApi5 {}
  interface PageQuickAndSimpleCachingWithApacheCommonsJcs {}
  interface PageRayKelleySilverStar {}
  interface PageRdfSyntaxExamples {}
  interface PageRenderTheKeysAndValuesFromAMapInFreemarker {}
  interface PageRespondToButtonClickWithObservable {}
  interface PageRigAMeshWithZspheresInZbrush {}
  interface PageSceneAndSequelPatternForWriters {}
  interface PageScriptForRotatingUnityGameObject90Degrees {}
  interface PageServeStaticResourcesWithSpringBoot {}
  interface PageSetThePageTitleInAngular {}
  interface PageShrinkWindowsVmOnVmwareFusionForMac {}
  interface PageSparqlExamplesAsk {}
  interface PageSparqlExamplesConstruct {}
  interface PageSparqlExamplesCountAllStatements {}
  interface PageSparqlExamplesDateRange {}
  interface PageSparqlExamplesFederation {}
  interface PageSparqlExamplesFilter {}
  interface PageSparqlExamplesInsert {}
  interface PageSparqlExamplesLimit {}
  interface PageSparqlExamplesListClasses {}
  interface PageSparqlExamplesNegation {}
  interface PageSparqlExamplesOrderBy {}
  interface PageSparqlExamplesPaging {}
  interface PageSparqlExamplesSelect {}
  interface PageStory {}
  interface PageTemplatePage {}
  interface PageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScripts {}
  interface PageUnityGetRigidbodyFromObject {}
  interface PageUnityPreferencesYourBuiltInKeyboardCheatSheet {}
  interface PageUnityRecipesFollowObject {}
  interface PageUnityRecipesHeadBobOrBreathe {}
  interface PageUnityRecipesLookTowardDirectionOfMovement {}
  interface PageUnityRecipesLookTowardDirectionOfVelocity {}
  interface PageUseAutoMaskingByPolygroupsInZbrush {}
  interface PageUseFibermeshInZbrush {}
  interface PageUseMicromeshInZbrush {}
  interface PageUsePrismJsInIonicStencilApp {}
  interface PageUseSpotlightToDisplayReferenceImagesInZbrush {}
  interface PageVietnam1967AmphibiousCombat {}
  interface PageWeldMultipleSubtoolsInZbrush {}
  interface PageXmlaccessSamples {}
  interface PageZbrushKeyboardShortcuts {}
  interface PageZbrushResourcesOnline {}

  interface IntrinsicElements {
    'app-404-page-not-found': App404PageNotFound;
    'app-blog-filter': AppBlogFilter;
    'app-entry-meta': AppEntryMeta;
    'app-photo-card': AppPhotoCard;
    'app-photos': AppPhotos;
    'app-root': AppRoot;
    'app-tabs': AppTabs;
    'page-7-quintessential-brushes-for-zbrush-beginners': Page7QuintessentialBrushesForZbrushBeginners;
    'page-7-reasons-why-typescript-helps-you-kick-ass': Page7ReasonsWhyTypescriptHelpsYouKickAss;
    'page-a-javascript-implementation-of-java-util-map': PageAJavascriptImplementationOfJavaUtilMap;
    'page-about': PageAbout;
    'page-apply-different-materials-to-subtools-in-zbrush': PageApplyDifferentMaterialsToSubtoolsInZbrush;
    'page-art': PageArt;
    'page-automatically-build-and-include-one-eclipse-project-into-another': PageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnother;
    'page-bend-things-in-zbrush-with-the-bend-curve-modifier': PageBendThingsInZbrushWithTheBendCurveModifier;
    'page-books': PageBooks;
    'page-cage': PageCage;
    'page-change-canvas-background-color-in-zbrush': PageChangeCanvasBackgroundColorInZbrush;
    'page-cmd-chron-beaver-cage': PageCmdChronBeaverCage;
    'page-confluence-panel-macro': PageConfluencePanelMacro;
    'page-convert-zbrush-polygroups-into-subtools': PageConvertZbrushPolygroupsIntoSubtools;
    'page-copy-assets-from-node-modules-in-stencil-js': PageCopyAssetsFromNodeModulesInStencilJs;
    'page-create-clothing-in-zbrush-extruding-masked-area': PageCreateClothingInZbrushExtrudingMaskedArea;
    'page-create-new-subtool-from-masked-area-in-zbrush': PageCreateNewSubtoolFromMaskedAreaInZbrush;
    'page-create-player-health-status-indicator-for-unity-gui-part-1': PageCreatePlayerHealthStatusIndicatorForUnityGuiPart1;
    'page-create-player-health-status-indicator-for-unity-gui-part-2': PageCreatePlayerHealthStatusIndicatorForUnityGuiPart2;
    'page-create-player-health-status-indicator-for-unity-gui-part-3': PageCreatePlayerHealthStatusIndicatorForUnityGuiPart3;
    'page-create-polygroup-from-mask-in-zbrush': PageCreatePolygroupFromMaskInZbrush;
    'page-delete-hidden-geometry-in-zbrush': PageDeleteHiddenGeometryInZbrush;
    'page-docker-cheat-sheet': PageDockerCheatSheet;
    'page-female-anatomy-out-of-the-box-in-zbrush': PageFemaleAnatomyOutOfTheBoxInZbrush;
    'page-find-java-classes-or-packages-contained-in-jar-files': PageFindJavaClassesOrPackagesContainedInJarFiles;
    'page-fix-for-git-after-macos-mojave-upgrade': PageFixForGitAfterMacosMojaveUpgrade;
    'page-format-currency-in-angular': PageFormatCurrencyInAngular;
    'page-getting-parts-of-a-url-from-the-httpservletrequest-object': PageGettingPartsOfAUrlFromTheHttpservletrequestObject;
    'page-home': PageHome;
    'page-how-to-apply-texture-in-zbrush': PageHowToApplyTextureInZbrush;
    'page-how-to-sketch-with-zspheres-in-zbrush': PageHowToSketchWithZspheresInZbrush;
    'page-how-to-use-live-boolean-in-zbrush': PageHowToUseLiveBooleanInZbrush;
    'page-index-of-item-within-angular-ngfor-loop': PageIndexOfItemWithinAngularNgforLoop;
    'page-install-java-plugin-for-64bit-firefox-on-centos-6-4': PageInstallJavaPluginFor64bitFirefoxOnCentos64;
    'page-install-oracle-java-8-on-ubuntu': PageInstallOracleJava8OnUbuntu;
    'page-isolate-a-polygroup-in-zbrush': PageIsolateAPolygroupInZbrush;
    'page-killing-kittens': PageKillingKittens;
    'page-life-events': PageLifeEvents;
    'page-list-ibm-db2-commands': PageListIbmDb2Commands;
    'page-logging-with-spring-boot': PageLoggingWithSpringBoot;
    'page-make-a-zbrush-speed-sculpt-timelapse-video': PageMakeAZbrushSpeedSculptTimelapseVideo;
    'page-mapping-to-a-view-in-spring-when-no-controller-logic-is-required': PageMappingToAViewInSpringWhenNoControllerLogicIsRequired;
    'page-mirror-polygroup-on-subtool-in-zbrush': PageMirrorPolygroupOnSubtoolInZbrush;
    'page-photos-weapons-platoon': PagePhotosWeaponsPlatoon;
    'page-pink-hearts': PagePinkHearts;
    'page-pwa-with-ionic-angular-wordpress-api-1': PagePwaWithIonicAngularWordpressApi1;
    'page-pwa-with-ionic-angular-wordpress-api-2': PagePwaWithIonicAngularWordpressApi2;
    'page-pwa-with-ionic-angular-wordpress-api-3': PagePwaWithIonicAngularWordpressApi3;
    'page-pwa-with-ionic-angular-wordpress-api-4': PagePwaWithIonicAngularWordpressApi4;
    'page-pwa-with-ionic-angular-wordpress-api-5': PagePwaWithIonicAngularWordpressApi5;
    'page-quick-and-simple-caching-with-apache-commons-jcs': PageQuickAndSimpleCachingWithApacheCommonsJcs;
    'page-ray-kelley-silver-star': PageRayKelleySilverStar;
    'page-rdf-syntax-examples': PageRdfSyntaxExamples;
    'page-render-the-keys-and-values-from-a-map-in-freemarker': PageRenderTheKeysAndValuesFromAMapInFreemarker;
    'page-respond-to-button-click-with-observable': PageRespondToButtonClickWithObservable;
    'page-rig-a-mesh-with-zspheres-in-zbrush': PageRigAMeshWithZspheresInZbrush;
    'page-scene-and-sequel-pattern-for-writers': PageSceneAndSequelPatternForWriters;
    'page-script-for-rotating-unity-game-object-90-degrees': PageScriptForRotatingUnityGameObject90Degrees;
    'page-serve-static-resources-with-spring-boot': PageServeStaticResourcesWithSpringBoot;
    'page-set-the-page-title-in-angular': PageSetThePageTitleInAngular;
    'page-shrink-windows-vm-on-vmware-fusion-for-mac': PageShrinkWindowsVmOnVmwareFusionForMac;
    'page-sparql-examples-ask': PageSparqlExamplesAsk;
    'page-sparql-examples-construct': PageSparqlExamplesConstruct;
    'page-sparql-examples-count-all-statements': PageSparqlExamplesCountAllStatements;
    'page-sparql-examples-date-range': PageSparqlExamplesDateRange;
    'page-sparql-examples-federation': PageSparqlExamplesFederation;
    'page-sparql-examples-filter': PageSparqlExamplesFilter;
    'page-sparql-examples-insert': PageSparqlExamplesInsert;
    'page-sparql-examples-limit': PageSparqlExamplesLimit;
    'page-sparql-examples-list-classes': PageSparqlExamplesListClasses;
    'page-sparql-examples-negation': PageSparqlExamplesNegation;
    'page-sparql-examples-order-by': PageSparqlExamplesOrderBy;
    'page-sparql-examples-paging': PageSparqlExamplesPaging;
    'page-sparql-examples-select': PageSparqlExamplesSelect;
    'page-story': PageStory;
    'page-template-page': PageTemplatePage;
    'page-unity-freebies-game-timer-cinematic-letterbox-and-fade-in-scripts': PageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScripts;
    'page-unity-get-rigidbody-from-object': PageUnityGetRigidbodyFromObject;
    'page-unity-preferences-your-built-in-keyboard-cheat-sheet': PageUnityPreferencesYourBuiltInKeyboardCheatSheet;
    'page-unity-recipes-follow-object': PageUnityRecipesFollowObject;
    'page-unity-recipes-head-bob-or-breathe': PageUnityRecipesHeadBobOrBreathe;
    'page-unity-recipes-look-toward-direction-of-movement': PageUnityRecipesLookTowardDirectionOfMovement;
    'page-unity-recipes-look-toward-direction-of-velocity': PageUnityRecipesLookTowardDirectionOfVelocity;
    'page-use-auto-masking-by-polygroups-in-zbrush': PageUseAutoMaskingByPolygroupsInZbrush;
    'page-use-fibermesh-in-zbrush': PageUseFibermeshInZbrush;
    'page-use-micromesh-in-zbrush': PageUseMicromeshInZbrush;
    'page-use-prism-js-in-ionic-stencil-app': PageUsePrismJsInIonicStencilApp;
    'page-use-spotlight-to-display-reference-images-in-zbrush': PageUseSpotlightToDisplayReferenceImagesInZbrush;
    'page-vietnam-1967-amphibious-combat': PageVietnam1967AmphibiousCombat;
    'page-weld-multiple-subtools-in-zbrush': PageWeldMultipleSubtoolsInZbrush;
    'page-xmlaccess-samples': PageXmlaccessSamples;
    'page-zbrush-keyboard-shortcuts': PageZbrushKeyboardShortcuts;
    'page-zbrush-resources-online': PageZbrushResourcesOnline;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-404-page-not-found': LocalJSX.App404PageNotFound & JSXBase.HTMLAttributes<HTMLApp404PageNotFoundElement>;
      'app-blog-filter': LocalJSX.AppBlogFilter & JSXBase.HTMLAttributes<HTMLAppBlogFilterElement>;
      'app-entry-meta': LocalJSX.AppEntryMeta & JSXBase.HTMLAttributes<HTMLAppEntryMetaElement>;
      'app-photo-card': LocalJSX.AppPhotoCard & JSXBase.HTMLAttributes<HTMLAppPhotoCardElement>;
      'app-photos': LocalJSX.AppPhotos & JSXBase.HTMLAttributes<HTMLAppPhotosElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-tabs': LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
      'page-7-quintessential-brushes-for-zbrush-beginners': LocalJSX.Page7QuintessentialBrushesForZbrushBeginners & JSXBase.HTMLAttributes<HTMLPage7QuintessentialBrushesForZbrushBeginnersElement>;
      'page-7-reasons-why-typescript-helps-you-kick-ass': LocalJSX.Page7ReasonsWhyTypescriptHelpsYouKickAss & JSXBase.HTMLAttributes<HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement>;
      'page-a-javascript-implementation-of-java-util-map': LocalJSX.PageAJavascriptImplementationOfJavaUtilMap & JSXBase.HTMLAttributes<HTMLPageAJavascriptImplementationOfJavaUtilMapElement>;
      'page-about': LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
      'page-apply-different-materials-to-subtools-in-zbrush': LocalJSX.PageApplyDifferentMaterialsToSubtoolsInZbrush & JSXBase.HTMLAttributes<HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement>;
      'page-art': LocalJSX.PageArt & JSXBase.HTMLAttributes<HTMLPageArtElement>;
      'page-automatically-build-and-include-one-eclipse-project-into-another': LocalJSX.PageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnother & JSXBase.HTMLAttributes<HTMLPageAutomaticallyBuildAndIncludeOneEclipseProjectIntoAnotherElement>;
      'page-bend-things-in-zbrush-with-the-bend-curve-modifier': LocalJSX.PageBendThingsInZbrushWithTheBendCurveModifier & JSXBase.HTMLAttributes<HTMLPageBendThingsInZbrushWithTheBendCurveModifierElement>;
      'page-books': LocalJSX.PageBooks & JSXBase.HTMLAttributes<HTMLPageBooksElement>;
      'page-cage': LocalJSX.PageCage & JSXBase.HTMLAttributes<HTMLPageCageElement>;
      'page-change-canvas-background-color-in-zbrush': LocalJSX.PageChangeCanvasBackgroundColorInZbrush & JSXBase.HTMLAttributes<HTMLPageChangeCanvasBackgroundColorInZbrushElement>;
      'page-cmd-chron-beaver-cage': LocalJSX.PageCmdChronBeaverCage & JSXBase.HTMLAttributes<HTMLPageCmdChronBeaverCageElement>;
      'page-confluence-panel-macro': LocalJSX.PageConfluencePanelMacro & JSXBase.HTMLAttributes<HTMLPageConfluencePanelMacroElement>;
      'page-convert-zbrush-polygroups-into-subtools': LocalJSX.PageConvertZbrushPolygroupsIntoSubtools & JSXBase.HTMLAttributes<HTMLPageConvertZbrushPolygroupsIntoSubtoolsElement>;
      'page-copy-assets-from-node-modules-in-stencil-js': LocalJSX.PageCopyAssetsFromNodeModulesInStencilJs & JSXBase.HTMLAttributes<HTMLPageCopyAssetsFromNodeModulesInStencilJsElement>;
      'page-create-clothing-in-zbrush-extruding-masked-area': LocalJSX.PageCreateClothingInZbrushExtrudingMaskedArea & JSXBase.HTMLAttributes<HTMLPageCreateClothingInZbrushExtrudingMaskedAreaElement>;
      'page-create-new-subtool-from-masked-area-in-zbrush': LocalJSX.PageCreateNewSubtoolFromMaskedAreaInZbrush & JSXBase.HTMLAttributes<HTMLPageCreateNewSubtoolFromMaskedAreaInZbrushElement>;
      'page-create-player-health-status-indicator-for-unity-gui-part-1': LocalJSX.PageCreatePlayerHealthStatusIndicatorForUnityGuiPart1 & JSXBase.HTMLAttributes<HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart1Element>;
      'page-create-player-health-status-indicator-for-unity-gui-part-2': LocalJSX.PageCreatePlayerHealthStatusIndicatorForUnityGuiPart2 & JSXBase.HTMLAttributes<HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart2Element>;
      'page-create-player-health-status-indicator-for-unity-gui-part-3': LocalJSX.PageCreatePlayerHealthStatusIndicatorForUnityGuiPart3 & JSXBase.HTMLAttributes<HTMLPageCreatePlayerHealthStatusIndicatorForUnityGuiPart3Element>;
      'page-create-polygroup-from-mask-in-zbrush': LocalJSX.PageCreatePolygroupFromMaskInZbrush & JSXBase.HTMLAttributes<HTMLPageCreatePolygroupFromMaskInZbrushElement>;
      'page-delete-hidden-geometry-in-zbrush': LocalJSX.PageDeleteHiddenGeometryInZbrush & JSXBase.HTMLAttributes<HTMLPageDeleteHiddenGeometryInZbrushElement>;
      'page-docker-cheat-sheet': LocalJSX.PageDockerCheatSheet & JSXBase.HTMLAttributes<HTMLPageDockerCheatSheetElement>;
      'page-female-anatomy-out-of-the-box-in-zbrush': LocalJSX.PageFemaleAnatomyOutOfTheBoxInZbrush & JSXBase.HTMLAttributes<HTMLPageFemaleAnatomyOutOfTheBoxInZbrushElement>;
      'page-find-java-classes-or-packages-contained-in-jar-files': LocalJSX.PageFindJavaClassesOrPackagesContainedInJarFiles & JSXBase.HTMLAttributes<HTMLPageFindJavaClassesOrPackagesContainedInJarFilesElement>;
      'page-fix-for-git-after-macos-mojave-upgrade': LocalJSX.PageFixForGitAfterMacosMojaveUpgrade & JSXBase.HTMLAttributes<HTMLPageFixForGitAfterMacosMojaveUpgradeElement>;
      'page-format-currency-in-angular': LocalJSX.PageFormatCurrencyInAngular & JSXBase.HTMLAttributes<HTMLPageFormatCurrencyInAngularElement>;
      'page-getting-parts-of-a-url-from-the-httpservletrequest-object': LocalJSX.PageGettingPartsOfAUrlFromTheHttpservletrequestObject & JSXBase.HTMLAttributes<HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement>;
      'page-home': LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
      'page-how-to-apply-texture-in-zbrush': LocalJSX.PageHowToApplyTextureInZbrush & JSXBase.HTMLAttributes<HTMLPageHowToApplyTextureInZbrushElement>;
      'page-how-to-sketch-with-zspheres-in-zbrush': LocalJSX.PageHowToSketchWithZspheresInZbrush & JSXBase.HTMLAttributes<HTMLPageHowToSketchWithZspheresInZbrushElement>;
      'page-how-to-use-live-boolean-in-zbrush': LocalJSX.PageHowToUseLiveBooleanInZbrush & JSXBase.HTMLAttributes<HTMLPageHowToUseLiveBooleanInZbrushElement>;
      'page-index-of-item-within-angular-ngfor-loop': LocalJSX.PageIndexOfItemWithinAngularNgforLoop & JSXBase.HTMLAttributes<HTMLPageIndexOfItemWithinAngularNgforLoopElement>;
      'page-install-java-plugin-for-64bit-firefox-on-centos-6-4': LocalJSX.PageInstallJavaPluginFor64bitFirefoxOnCentos64 & JSXBase.HTMLAttributes<HTMLPageInstallJavaPluginFor64bitFirefoxOnCentos64Element>;
      'page-install-oracle-java-8-on-ubuntu': LocalJSX.PageInstallOracleJava8OnUbuntu & JSXBase.HTMLAttributes<HTMLPageInstallOracleJava8OnUbuntuElement>;
      'page-isolate-a-polygroup-in-zbrush': LocalJSX.PageIsolateAPolygroupInZbrush & JSXBase.HTMLAttributes<HTMLPageIsolateAPolygroupInZbrushElement>;
      'page-killing-kittens': LocalJSX.PageKillingKittens & JSXBase.HTMLAttributes<HTMLPageKillingKittensElement>;
      'page-life-events': LocalJSX.PageLifeEvents & JSXBase.HTMLAttributes<HTMLPageLifeEventsElement>;
      'page-list-ibm-db2-commands': LocalJSX.PageListIbmDb2Commands & JSXBase.HTMLAttributes<HTMLPageListIbmDb2CommandsElement>;
      'page-logging-with-spring-boot': LocalJSX.PageLoggingWithSpringBoot & JSXBase.HTMLAttributes<HTMLPageLoggingWithSpringBootElement>;
      'page-make-a-zbrush-speed-sculpt-timelapse-video': LocalJSX.PageMakeAZbrushSpeedSculptTimelapseVideo & JSXBase.HTMLAttributes<HTMLPageMakeAZbrushSpeedSculptTimelapseVideoElement>;
      'page-mapping-to-a-view-in-spring-when-no-controller-logic-is-required': LocalJSX.PageMappingToAViewInSpringWhenNoControllerLogicIsRequired & JSXBase.HTMLAttributes<HTMLPageMappingToAViewInSpringWhenNoControllerLogicIsRequiredElement>;
      'page-mirror-polygroup-on-subtool-in-zbrush': LocalJSX.PageMirrorPolygroupOnSubtoolInZbrush & JSXBase.HTMLAttributes<HTMLPageMirrorPolygroupOnSubtoolInZbrushElement>;
      'page-photos-weapons-platoon': LocalJSX.PagePhotosWeaponsPlatoon & JSXBase.HTMLAttributes<HTMLPagePhotosWeaponsPlatoonElement>;
      'page-pink-hearts': LocalJSX.PagePinkHearts & JSXBase.HTMLAttributes<HTMLPagePinkHeartsElement>;
      'page-pwa-with-ionic-angular-wordpress-api-1': LocalJSX.PagePwaWithIonicAngularWordpressApi1 & JSXBase.HTMLAttributes<HTMLPagePwaWithIonicAngularWordpressApi1Element>;
      'page-pwa-with-ionic-angular-wordpress-api-2': LocalJSX.PagePwaWithIonicAngularWordpressApi2 & JSXBase.HTMLAttributes<HTMLPagePwaWithIonicAngularWordpressApi2Element>;
      'page-pwa-with-ionic-angular-wordpress-api-3': LocalJSX.PagePwaWithIonicAngularWordpressApi3 & JSXBase.HTMLAttributes<HTMLPagePwaWithIonicAngularWordpressApi3Element>;
      'page-pwa-with-ionic-angular-wordpress-api-4': LocalJSX.PagePwaWithIonicAngularWordpressApi4 & JSXBase.HTMLAttributes<HTMLPagePwaWithIonicAngularWordpressApi4Element>;
      'page-pwa-with-ionic-angular-wordpress-api-5': LocalJSX.PagePwaWithIonicAngularWordpressApi5 & JSXBase.HTMLAttributes<HTMLPagePwaWithIonicAngularWordpressApi5Element>;
      'page-quick-and-simple-caching-with-apache-commons-jcs': LocalJSX.PageQuickAndSimpleCachingWithApacheCommonsJcs & JSXBase.HTMLAttributes<HTMLPageQuickAndSimpleCachingWithApacheCommonsJcsElement>;
      'page-ray-kelley-silver-star': LocalJSX.PageRayKelleySilverStar & JSXBase.HTMLAttributes<HTMLPageRayKelleySilverStarElement>;
      'page-rdf-syntax-examples': LocalJSX.PageRdfSyntaxExamples & JSXBase.HTMLAttributes<HTMLPageRdfSyntaxExamplesElement>;
      'page-render-the-keys-and-values-from-a-map-in-freemarker': LocalJSX.PageRenderTheKeysAndValuesFromAMapInFreemarker & JSXBase.HTMLAttributes<HTMLPageRenderTheKeysAndValuesFromAMapInFreemarkerElement>;
      'page-respond-to-button-click-with-observable': LocalJSX.PageRespondToButtonClickWithObservable & JSXBase.HTMLAttributes<HTMLPageRespondToButtonClickWithObservableElement>;
      'page-rig-a-mesh-with-zspheres-in-zbrush': LocalJSX.PageRigAMeshWithZspheresInZbrush & JSXBase.HTMLAttributes<HTMLPageRigAMeshWithZspheresInZbrushElement>;
      'page-scene-and-sequel-pattern-for-writers': LocalJSX.PageSceneAndSequelPatternForWriters & JSXBase.HTMLAttributes<HTMLPageSceneAndSequelPatternForWritersElement>;
      'page-script-for-rotating-unity-game-object-90-degrees': LocalJSX.PageScriptForRotatingUnityGameObject90Degrees & JSXBase.HTMLAttributes<HTMLPageScriptForRotatingUnityGameObject90DegreesElement>;
      'page-serve-static-resources-with-spring-boot': LocalJSX.PageServeStaticResourcesWithSpringBoot & JSXBase.HTMLAttributes<HTMLPageServeStaticResourcesWithSpringBootElement>;
      'page-set-the-page-title-in-angular': LocalJSX.PageSetThePageTitleInAngular & JSXBase.HTMLAttributes<HTMLPageSetThePageTitleInAngularElement>;
      'page-shrink-windows-vm-on-vmware-fusion-for-mac': LocalJSX.PageShrinkWindowsVmOnVmwareFusionForMac & JSXBase.HTMLAttributes<HTMLPageShrinkWindowsVmOnVmwareFusionForMacElement>;
      'page-sparql-examples-ask': LocalJSX.PageSparqlExamplesAsk & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesAskElement>;
      'page-sparql-examples-construct': LocalJSX.PageSparqlExamplesConstruct & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesConstructElement>;
      'page-sparql-examples-count-all-statements': LocalJSX.PageSparqlExamplesCountAllStatements & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesCountAllStatementsElement>;
      'page-sparql-examples-date-range': LocalJSX.PageSparqlExamplesDateRange & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesDateRangeElement>;
      'page-sparql-examples-federation': LocalJSX.PageSparqlExamplesFederation & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesFederationElement>;
      'page-sparql-examples-filter': LocalJSX.PageSparqlExamplesFilter & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesFilterElement>;
      'page-sparql-examples-insert': LocalJSX.PageSparqlExamplesInsert & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesInsertElement>;
      'page-sparql-examples-limit': LocalJSX.PageSparqlExamplesLimit & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesLimitElement>;
      'page-sparql-examples-list-classes': LocalJSX.PageSparqlExamplesListClasses & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesListClassesElement>;
      'page-sparql-examples-negation': LocalJSX.PageSparqlExamplesNegation & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesNegationElement>;
      'page-sparql-examples-order-by': LocalJSX.PageSparqlExamplesOrderBy & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesOrderByElement>;
      'page-sparql-examples-paging': LocalJSX.PageSparqlExamplesPaging & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesPagingElement>;
      'page-sparql-examples-select': LocalJSX.PageSparqlExamplesSelect & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesSelectElement>;
      'page-story': LocalJSX.PageStory & JSXBase.HTMLAttributes<HTMLPageStoryElement>;
      'page-template-page': LocalJSX.PageTemplatePage & JSXBase.HTMLAttributes<HTMLPageTemplatePageElement>;
      'page-unity-freebies-game-timer-cinematic-letterbox-and-fade-in-scripts': LocalJSX.PageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScripts & JSXBase.HTMLAttributes<HTMLPageUnityFreebiesGameTimerCinematicLetterboxAndFadeInScriptsElement>;
      'page-unity-get-rigidbody-from-object': LocalJSX.PageUnityGetRigidbodyFromObject & JSXBase.HTMLAttributes<HTMLPageUnityGetRigidbodyFromObjectElement>;
      'page-unity-preferences-your-built-in-keyboard-cheat-sheet': LocalJSX.PageUnityPreferencesYourBuiltInKeyboardCheatSheet & JSXBase.HTMLAttributes<HTMLPageUnityPreferencesYourBuiltInKeyboardCheatSheetElement>;
      'page-unity-recipes-follow-object': LocalJSX.PageUnityRecipesFollowObject & JSXBase.HTMLAttributes<HTMLPageUnityRecipesFollowObjectElement>;
      'page-unity-recipes-head-bob-or-breathe': LocalJSX.PageUnityRecipesHeadBobOrBreathe & JSXBase.HTMLAttributes<HTMLPageUnityRecipesHeadBobOrBreatheElement>;
      'page-unity-recipes-look-toward-direction-of-movement': LocalJSX.PageUnityRecipesLookTowardDirectionOfMovement & JSXBase.HTMLAttributes<HTMLPageUnityRecipesLookTowardDirectionOfMovementElement>;
      'page-unity-recipes-look-toward-direction-of-velocity': LocalJSX.PageUnityRecipesLookTowardDirectionOfVelocity & JSXBase.HTMLAttributes<HTMLPageUnityRecipesLookTowardDirectionOfVelocityElement>;
      'page-use-auto-masking-by-polygroups-in-zbrush': LocalJSX.PageUseAutoMaskingByPolygroupsInZbrush & JSXBase.HTMLAttributes<HTMLPageUseAutoMaskingByPolygroupsInZbrushElement>;
      'page-use-fibermesh-in-zbrush': LocalJSX.PageUseFibermeshInZbrush & JSXBase.HTMLAttributes<HTMLPageUseFibermeshInZbrushElement>;
      'page-use-micromesh-in-zbrush': LocalJSX.PageUseMicromeshInZbrush & JSXBase.HTMLAttributes<HTMLPageUseMicromeshInZbrushElement>;
      'page-use-prism-js-in-ionic-stencil-app': LocalJSX.PageUsePrismJsInIonicStencilApp & JSXBase.HTMLAttributes<HTMLPageUsePrismJsInIonicStencilAppElement>;
      'page-use-spotlight-to-display-reference-images-in-zbrush': LocalJSX.PageUseSpotlightToDisplayReferenceImagesInZbrush & JSXBase.HTMLAttributes<HTMLPageUseSpotlightToDisplayReferenceImagesInZbrushElement>;
      'page-vietnam-1967-amphibious-combat': LocalJSX.PageVietnam1967AmphibiousCombat & JSXBase.HTMLAttributes<HTMLPageVietnam1967AmphibiousCombatElement>;
      'page-weld-multiple-subtools-in-zbrush': LocalJSX.PageWeldMultipleSubtoolsInZbrush & JSXBase.HTMLAttributes<HTMLPageWeldMultipleSubtoolsInZbrushElement>;
      'page-xmlaccess-samples': LocalJSX.PageXmlaccessSamples & JSXBase.HTMLAttributes<HTMLPageXmlaccessSamplesElement>;
      'page-zbrush-keyboard-shortcuts': LocalJSX.PageZbrushKeyboardShortcuts & JSXBase.HTMLAttributes<HTMLPageZbrushKeyboardShortcutsElement>;
      'page-zbrush-resources-online': LocalJSX.PageZbrushResourcesOnline & JSXBase.HTMLAttributes<HTMLPageZbrushResourcesOnlineElement>;
    }
  }
}


