/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppBlogPost {
    'name': string;
  }
  interface AppPhotoCard {
    'imagePath': string;
    'item': any;
  }
  interface AppPhotos {
    'name': string;
  }
  interface AppRoot {}
  interface Page7ReasonsWhyTypescriptHelpsYouKickAss {}
  interface PageAbout {}
  interface PageApplyDifferentMaterialsToSubtoolsInZbrush {}
  interface PageArt {}
  interface PageBlog {}
  interface PageBlogFilter {
    'excludedTracks': string[];
  }
  interface PageBooks {}
  interface PageCage {}
  interface PageCmdChronBeaverCage {}
  interface PageFormatCurrencyInAngular {}
  interface PageGettingPartsOfAUrlFromTheHttpservletrequestObject {}
  interface PageIndexOfItemWithinAngularNgforLoop {}
  interface PageIsolateAPolygroupInZbrush {}
  interface PageKillingKittens {}
  interface PageListIbmDb2Commands {}
  interface PagePhotosWeaponsPlatoon {}
  interface PagePwaWithIonicAngularWordpressApi1 {}
  interface PageRayKelleySilverStar {}
  interface PageRespondToButtonClickWithObservable {}
  interface PageSparqlExamplesAsk {}
  interface PageSparqlExamplesConstruct {}
  interface PageSparqlExamplesCountAllStatements {}
  interface PageSparqlExamplesDateRange {}
  interface PageSparqlExamplesFederation {}
  interface PageSparqlExamplesFilter {}
  interface PageSparqlExamplesInsert {}
  interface PageSparqlExamplesLimit {}
  interface PageSparqlExamplesListClasses {}
  interface PageSparqlExamplesNegation {}
  interface PageSparqlExamplesOrderBy {}
  interface PageSparqlExamplesPaging {}
  interface PageSparqlExamplesSelect {}
  interface PageTabs {}
  interface PageTemplatePage {}
  interface PageUsePrismJsInIonicStencilApp {}
  interface PageVietnam1967AmphibiousCombat {}
  interface PageZbrushKeyboardShortcuts {}
}

declare global {


  interface HTMLAppBlogPostElement extends Components.AppBlogPost, HTMLStencilElement {}
  var HTMLAppBlogPostElement: {
    prototype: HTMLAppBlogPostElement;
    new (): HTMLAppBlogPostElement;
  };

  interface HTMLAppPhotoCardElement extends Components.AppPhotoCard, HTMLStencilElement {}
  var HTMLAppPhotoCardElement: {
    prototype: HTMLAppPhotoCardElement;
    new (): HTMLAppPhotoCardElement;
  };

  interface HTMLAppPhotosElement extends Components.AppPhotos, HTMLStencilElement {}
  var HTMLAppPhotosElement: {
    prototype: HTMLAppPhotosElement;
    new (): HTMLAppPhotosElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement extends Components.Page7ReasonsWhyTypescriptHelpsYouKickAss, HTMLStencilElement {}
  var HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement: {
    prototype: HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement;
    new (): HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement;
  };

  interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {}
  var HTMLPageAboutElement: {
    prototype: HTMLPageAboutElement;
    new (): HTMLPageAboutElement;
  };

  interface HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement extends Components.PageApplyDifferentMaterialsToSubtoolsInZbrush, HTMLStencilElement {}
  var HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement: {
    prototype: HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement;
    new (): HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement;
  };

  interface HTMLPageArtElement extends Components.PageArt, HTMLStencilElement {}
  var HTMLPageArtElement: {
    prototype: HTMLPageArtElement;
    new (): HTMLPageArtElement;
  };

  interface HTMLPageBlogElement extends Components.PageBlog, HTMLStencilElement {}
  var HTMLPageBlogElement: {
    prototype: HTMLPageBlogElement;
    new (): HTMLPageBlogElement;
  };

  interface HTMLPageBlogFilterElement extends Components.PageBlogFilter, HTMLStencilElement {}
  var HTMLPageBlogFilterElement: {
    prototype: HTMLPageBlogFilterElement;
    new (): HTMLPageBlogFilterElement;
  };

  interface HTMLPageBooksElement extends Components.PageBooks, HTMLStencilElement {}
  var HTMLPageBooksElement: {
    prototype: HTMLPageBooksElement;
    new (): HTMLPageBooksElement;
  };

  interface HTMLPageCageElement extends Components.PageCage, HTMLStencilElement {}
  var HTMLPageCageElement: {
    prototype: HTMLPageCageElement;
    new (): HTMLPageCageElement;
  };

  interface HTMLPageCmdChronBeaverCageElement extends Components.PageCmdChronBeaverCage, HTMLStencilElement {}
  var HTMLPageCmdChronBeaverCageElement: {
    prototype: HTMLPageCmdChronBeaverCageElement;
    new (): HTMLPageCmdChronBeaverCageElement;
  };

  interface HTMLPageFormatCurrencyInAngularElement extends Components.PageFormatCurrencyInAngular, HTMLStencilElement {}
  var HTMLPageFormatCurrencyInAngularElement: {
    prototype: HTMLPageFormatCurrencyInAngularElement;
    new (): HTMLPageFormatCurrencyInAngularElement;
  };

  interface HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement extends Components.PageGettingPartsOfAUrlFromTheHttpservletrequestObject, HTMLStencilElement {}
  var HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement: {
    prototype: HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement;
    new (): HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement;
  };

  interface HTMLPageIndexOfItemWithinAngularNgforLoopElement extends Components.PageIndexOfItemWithinAngularNgforLoop, HTMLStencilElement {}
  var HTMLPageIndexOfItemWithinAngularNgforLoopElement: {
    prototype: HTMLPageIndexOfItemWithinAngularNgforLoopElement;
    new (): HTMLPageIndexOfItemWithinAngularNgforLoopElement;
  };

  interface HTMLPageIsolateAPolygroupInZbrushElement extends Components.PageIsolateAPolygroupInZbrush, HTMLStencilElement {}
  var HTMLPageIsolateAPolygroupInZbrushElement: {
    prototype: HTMLPageIsolateAPolygroupInZbrushElement;
    new (): HTMLPageIsolateAPolygroupInZbrushElement;
  };

  interface HTMLPageKillingKittensElement extends Components.PageKillingKittens, HTMLStencilElement {}
  var HTMLPageKillingKittensElement: {
    prototype: HTMLPageKillingKittensElement;
    new (): HTMLPageKillingKittensElement;
  };

  interface HTMLPageListIbmDb2CommandsElement extends Components.PageListIbmDb2Commands, HTMLStencilElement {}
  var HTMLPageListIbmDb2CommandsElement: {
    prototype: HTMLPageListIbmDb2CommandsElement;
    new (): HTMLPageListIbmDb2CommandsElement;
  };

  interface HTMLPagePhotosWeaponsPlatoonElement extends Components.PagePhotosWeaponsPlatoon, HTMLStencilElement {}
  var HTMLPagePhotosWeaponsPlatoonElement: {
    prototype: HTMLPagePhotosWeaponsPlatoonElement;
    new (): HTMLPagePhotosWeaponsPlatoonElement;
  };

  interface HTMLPagePwaWithIonicAngularWordpressApi1Element extends Components.PagePwaWithIonicAngularWordpressApi1, HTMLStencilElement {}
  var HTMLPagePwaWithIonicAngularWordpressApi1Element: {
    prototype: HTMLPagePwaWithIonicAngularWordpressApi1Element;
    new (): HTMLPagePwaWithIonicAngularWordpressApi1Element;
  };

  interface HTMLPageRayKelleySilverStarElement extends Components.PageRayKelleySilverStar, HTMLStencilElement {}
  var HTMLPageRayKelleySilverStarElement: {
    prototype: HTMLPageRayKelleySilverStarElement;
    new (): HTMLPageRayKelleySilverStarElement;
  };

  interface HTMLPageRespondToButtonClickWithObservableElement extends Components.PageRespondToButtonClickWithObservable, HTMLStencilElement {}
  var HTMLPageRespondToButtonClickWithObservableElement: {
    prototype: HTMLPageRespondToButtonClickWithObservableElement;
    new (): HTMLPageRespondToButtonClickWithObservableElement;
  };

  interface HTMLPageSparqlExamplesAskElement extends Components.PageSparqlExamplesAsk, HTMLStencilElement {}
  var HTMLPageSparqlExamplesAskElement: {
    prototype: HTMLPageSparqlExamplesAskElement;
    new (): HTMLPageSparqlExamplesAskElement;
  };

  interface HTMLPageSparqlExamplesConstructElement extends Components.PageSparqlExamplesConstruct, HTMLStencilElement {}
  var HTMLPageSparqlExamplesConstructElement: {
    prototype: HTMLPageSparqlExamplesConstructElement;
    new (): HTMLPageSparqlExamplesConstructElement;
  };

  interface HTMLPageSparqlExamplesCountAllStatementsElement extends Components.PageSparqlExamplesCountAllStatements, HTMLStencilElement {}
  var HTMLPageSparqlExamplesCountAllStatementsElement: {
    prototype: HTMLPageSparqlExamplesCountAllStatementsElement;
    new (): HTMLPageSparqlExamplesCountAllStatementsElement;
  };

  interface HTMLPageSparqlExamplesDateRangeElement extends Components.PageSparqlExamplesDateRange, HTMLStencilElement {}
  var HTMLPageSparqlExamplesDateRangeElement: {
    prototype: HTMLPageSparqlExamplesDateRangeElement;
    new (): HTMLPageSparqlExamplesDateRangeElement;
  };

  interface HTMLPageSparqlExamplesFederationElement extends Components.PageSparqlExamplesFederation, HTMLStencilElement {}
  var HTMLPageSparqlExamplesFederationElement: {
    prototype: HTMLPageSparqlExamplesFederationElement;
    new (): HTMLPageSparqlExamplesFederationElement;
  };

  interface HTMLPageSparqlExamplesFilterElement extends Components.PageSparqlExamplesFilter, HTMLStencilElement {}
  var HTMLPageSparqlExamplesFilterElement: {
    prototype: HTMLPageSparqlExamplesFilterElement;
    new (): HTMLPageSparqlExamplesFilterElement;
  };

  interface HTMLPageSparqlExamplesInsertElement extends Components.PageSparqlExamplesInsert, HTMLStencilElement {}
  var HTMLPageSparqlExamplesInsertElement: {
    prototype: HTMLPageSparqlExamplesInsertElement;
    new (): HTMLPageSparqlExamplesInsertElement;
  };

  interface HTMLPageSparqlExamplesLimitElement extends Components.PageSparqlExamplesLimit, HTMLStencilElement {}
  var HTMLPageSparqlExamplesLimitElement: {
    prototype: HTMLPageSparqlExamplesLimitElement;
    new (): HTMLPageSparqlExamplesLimitElement;
  };

  interface HTMLPageSparqlExamplesListClassesElement extends Components.PageSparqlExamplesListClasses, HTMLStencilElement {}
  var HTMLPageSparqlExamplesListClassesElement: {
    prototype: HTMLPageSparqlExamplesListClassesElement;
    new (): HTMLPageSparqlExamplesListClassesElement;
  };

  interface HTMLPageSparqlExamplesNegationElement extends Components.PageSparqlExamplesNegation, HTMLStencilElement {}
  var HTMLPageSparqlExamplesNegationElement: {
    prototype: HTMLPageSparqlExamplesNegationElement;
    new (): HTMLPageSparqlExamplesNegationElement;
  };

  interface HTMLPageSparqlExamplesOrderByElement extends Components.PageSparqlExamplesOrderBy, HTMLStencilElement {}
  var HTMLPageSparqlExamplesOrderByElement: {
    prototype: HTMLPageSparqlExamplesOrderByElement;
    new (): HTMLPageSparqlExamplesOrderByElement;
  };

  interface HTMLPageSparqlExamplesPagingElement extends Components.PageSparqlExamplesPaging, HTMLStencilElement {}
  var HTMLPageSparqlExamplesPagingElement: {
    prototype: HTMLPageSparqlExamplesPagingElement;
    new (): HTMLPageSparqlExamplesPagingElement;
  };

  interface HTMLPageSparqlExamplesSelectElement extends Components.PageSparqlExamplesSelect, HTMLStencilElement {}
  var HTMLPageSparqlExamplesSelectElement: {
    prototype: HTMLPageSparqlExamplesSelectElement;
    new (): HTMLPageSparqlExamplesSelectElement;
  };

  interface HTMLPageTabsElement extends Components.PageTabs, HTMLStencilElement {}
  var HTMLPageTabsElement: {
    prototype: HTMLPageTabsElement;
    new (): HTMLPageTabsElement;
  };

  interface HTMLPageTemplatePageElement extends Components.PageTemplatePage, HTMLStencilElement {}
  var HTMLPageTemplatePageElement: {
    prototype: HTMLPageTemplatePageElement;
    new (): HTMLPageTemplatePageElement;
  };

  interface HTMLPageUsePrismJsInIonicStencilAppElement extends Components.PageUsePrismJsInIonicStencilApp, HTMLStencilElement {}
  var HTMLPageUsePrismJsInIonicStencilAppElement: {
    prototype: HTMLPageUsePrismJsInIonicStencilAppElement;
    new (): HTMLPageUsePrismJsInIonicStencilAppElement;
  };

  interface HTMLPageVietnam1967AmphibiousCombatElement extends Components.PageVietnam1967AmphibiousCombat, HTMLStencilElement {}
  var HTMLPageVietnam1967AmphibiousCombatElement: {
    prototype: HTMLPageVietnam1967AmphibiousCombatElement;
    new (): HTMLPageVietnam1967AmphibiousCombatElement;
  };

  interface HTMLPageZbrushKeyboardShortcutsElement extends Components.PageZbrushKeyboardShortcuts, HTMLStencilElement {}
  var HTMLPageZbrushKeyboardShortcutsElement: {
    prototype: HTMLPageZbrushKeyboardShortcutsElement;
    new (): HTMLPageZbrushKeyboardShortcutsElement;
  };
  interface HTMLElementTagNameMap {
    'app-blog-post': HTMLAppBlogPostElement;
    'app-photo-card': HTMLAppPhotoCardElement;
    'app-photos': HTMLAppPhotosElement;
    'app-root': HTMLAppRootElement;
    'page-7-reasons-why-typescript-helps-you-kick-ass': HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement;
    'page-about': HTMLPageAboutElement;
    'page-apply-different-materials-to-subtools-in-zbrush': HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement;
    'page-art': HTMLPageArtElement;
    'page-blog': HTMLPageBlogElement;
    'page-blog-filter': HTMLPageBlogFilterElement;
    'page-books': HTMLPageBooksElement;
    'page-cage': HTMLPageCageElement;
    'page-cmd-chron-beaver-cage': HTMLPageCmdChronBeaverCageElement;
    'page-format-currency-in-angular': HTMLPageFormatCurrencyInAngularElement;
    'page-getting-parts-of-a-url-from-the-httpservletrequest-object': HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement;
    'page-index-of-item-within-angular-ngfor-loop': HTMLPageIndexOfItemWithinAngularNgforLoopElement;
    'page-isolate-a-polygroup-in-zbrush': HTMLPageIsolateAPolygroupInZbrushElement;
    'page-killing-kittens': HTMLPageKillingKittensElement;
    'page-list-ibm-db2-commands': HTMLPageListIbmDb2CommandsElement;
    'page-photos-weapons-platoon': HTMLPagePhotosWeaponsPlatoonElement;
    'page-pwa-with-ionic-angular-wordpress-api-1': HTMLPagePwaWithIonicAngularWordpressApi1Element;
    'page-ray-kelley-silver-star': HTMLPageRayKelleySilverStarElement;
    'page-respond-to-button-click-with-observable': HTMLPageRespondToButtonClickWithObservableElement;
    'page-sparql-examples-ask': HTMLPageSparqlExamplesAskElement;
    'page-sparql-examples-construct': HTMLPageSparqlExamplesConstructElement;
    'page-sparql-examples-count-all-statements': HTMLPageSparqlExamplesCountAllStatementsElement;
    'page-sparql-examples-date-range': HTMLPageSparqlExamplesDateRangeElement;
    'page-sparql-examples-federation': HTMLPageSparqlExamplesFederationElement;
    'page-sparql-examples-filter': HTMLPageSparqlExamplesFilterElement;
    'page-sparql-examples-insert': HTMLPageSparqlExamplesInsertElement;
    'page-sparql-examples-limit': HTMLPageSparqlExamplesLimitElement;
    'page-sparql-examples-list-classes': HTMLPageSparqlExamplesListClassesElement;
    'page-sparql-examples-negation': HTMLPageSparqlExamplesNegationElement;
    'page-sparql-examples-order-by': HTMLPageSparqlExamplesOrderByElement;
    'page-sparql-examples-paging': HTMLPageSparqlExamplesPagingElement;
    'page-sparql-examples-select': HTMLPageSparqlExamplesSelectElement;
    'page-tabs': HTMLPageTabsElement;
    'page-template-page': HTMLPageTemplatePageElement;
    'page-use-prism-js-in-ionic-stencil-app': HTMLPageUsePrismJsInIonicStencilAppElement;
    'page-vietnam-1967-amphibious-combat': HTMLPageVietnam1967AmphibiousCombatElement;
    'page-zbrush-keyboard-shortcuts': HTMLPageZbrushKeyboardShortcutsElement;
  }
}

declare namespace LocalJSX {
  interface AppBlogPost {
    'name'?: string;
  }
  interface AppPhotoCard {
    'imagePath'?: string;
    'item'?: any;
  }
  interface AppPhotos {
    'name'?: string;
  }
  interface AppRoot {}
  interface Page7ReasonsWhyTypescriptHelpsYouKickAss {}
  interface PageAbout {}
  interface PageApplyDifferentMaterialsToSubtoolsInZbrush {}
  interface PageArt {}
  interface PageBlog {}
  interface PageBlogFilter {
    'excludedTracks'?: string[];
  }
  interface PageBooks {}
  interface PageCage {}
  interface PageCmdChronBeaverCage {}
  interface PageFormatCurrencyInAngular {}
  interface PageGettingPartsOfAUrlFromTheHttpservletrequestObject {}
  interface PageIndexOfItemWithinAngularNgforLoop {}
  interface PageIsolateAPolygroupInZbrush {}
  interface PageKillingKittens {}
  interface PageListIbmDb2Commands {}
  interface PagePhotosWeaponsPlatoon {}
  interface PagePwaWithIonicAngularWordpressApi1 {}
  interface PageRayKelleySilverStar {}
  interface PageRespondToButtonClickWithObservable {}
  interface PageSparqlExamplesAsk {}
  interface PageSparqlExamplesConstruct {}
  interface PageSparqlExamplesCountAllStatements {}
  interface PageSparqlExamplesDateRange {}
  interface PageSparqlExamplesFederation {}
  interface PageSparqlExamplesFilter {}
  interface PageSparqlExamplesInsert {}
  interface PageSparqlExamplesLimit {}
  interface PageSparqlExamplesListClasses {}
  interface PageSparqlExamplesNegation {}
  interface PageSparqlExamplesOrderBy {}
  interface PageSparqlExamplesPaging {}
  interface PageSparqlExamplesSelect {}
  interface PageTabs {}
  interface PageTemplatePage {}
  interface PageUsePrismJsInIonicStencilApp {}
  interface PageVietnam1967AmphibiousCombat {}
  interface PageZbrushKeyboardShortcuts {}

  interface IntrinsicElements {
    'app-blog-post': AppBlogPost;
    'app-photo-card': AppPhotoCard;
    'app-photos': AppPhotos;
    'app-root': AppRoot;
    'page-7-reasons-why-typescript-helps-you-kick-ass': Page7ReasonsWhyTypescriptHelpsYouKickAss;
    'page-about': PageAbout;
    'page-apply-different-materials-to-subtools-in-zbrush': PageApplyDifferentMaterialsToSubtoolsInZbrush;
    'page-art': PageArt;
    'page-blog': PageBlog;
    'page-blog-filter': PageBlogFilter;
    'page-books': PageBooks;
    'page-cage': PageCage;
    'page-cmd-chron-beaver-cage': PageCmdChronBeaverCage;
    'page-format-currency-in-angular': PageFormatCurrencyInAngular;
    'page-getting-parts-of-a-url-from-the-httpservletrequest-object': PageGettingPartsOfAUrlFromTheHttpservletrequestObject;
    'page-index-of-item-within-angular-ngfor-loop': PageIndexOfItemWithinAngularNgforLoop;
    'page-isolate-a-polygroup-in-zbrush': PageIsolateAPolygroupInZbrush;
    'page-killing-kittens': PageKillingKittens;
    'page-list-ibm-db2-commands': PageListIbmDb2Commands;
    'page-photos-weapons-platoon': PagePhotosWeaponsPlatoon;
    'page-pwa-with-ionic-angular-wordpress-api-1': PagePwaWithIonicAngularWordpressApi1;
    'page-ray-kelley-silver-star': PageRayKelleySilverStar;
    'page-respond-to-button-click-with-observable': PageRespondToButtonClickWithObservable;
    'page-sparql-examples-ask': PageSparqlExamplesAsk;
    'page-sparql-examples-construct': PageSparqlExamplesConstruct;
    'page-sparql-examples-count-all-statements': PageSparqlExamplesCountAllStatements;
    'page-sparql-examples-date-range': PageSparqlExamplesDateRange;
    'page-sparql-examples-federation': PageSparqlExamplesFederation;
    'page-sparql-examples-filter': PageSparqlExamplesFilter;
    'page-sparql-examples-insert': PageSparqlExamplesInsert;
    'page-sparql-examples-limit': PageSparqlExamplesLimit;
    'page-sparql-examples-list-classes': PageSparqlExamplesListClasses;
    'page-sparql-examples-negation': PageSparqlExamplesNegation;
    'page-sparql-examples-order-by': PageSparqlExamplesOrderBy;
    'page-sparql-examples-paging': PageSparqlExamplesPaging;
    'page-sparql-examples-select': PageSparqlExamplesSelect;
    'page-tabs': PageTabs;
    'page-template-page': PageTemplatePage;
    'page-use-prism-js-in-ionic-stencil-app': PageUsePrismJsInIonicStencilApp;
    'page-vietnam-1967-amphibious-combat': PageVietnam1967AmphibiousCombat;
    'page-zbrush-keyboard-shortcuts': PageZbrushKeyboardShortcuts;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-blog-post': LocalJSX.AppBlogPost & JSXBase.HTMLAttributes<HTMLAppBlogPostElement>;
      'app-photo-card': LocalJSX.AppPhotoCard & JSXBase.HTMLAttributes<HTMLAppPhotoCardElement>;
      'app-photos': LocalJSX.AppPhotos & JSXBase.HTMLAttributes<HTMLAppPhotosElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'page-7-reasons-why-typescript-helps-you-kick-ass': LocalJSX.Page7ReasonsWhyTypescriptHelpsYouKickAss & JSXBase.HTMLAttributes<HTMLPage7ReasonsWhyTypescriptHelpsYouKickAssElement>;
      'page-about': LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
      'page-apply-different-materials-to-subtools-in-zbrush': LocalJSX.PageApplyDifferentMaterialsToSubtoolsInZbrush & JSXBase.HTMLAttributes<HTMLPageApplyDifferentMaterialsToSubtoolsInZbrushElement>;
      'page-art': LocalJSX.PageArt & JSXBase.HTMLAttributes<HTMLPageArtElement>;
      'page-blog': LocalJSX.PageBlog & JSXBase.HTMLAttributes<HTMLPageBlogElement>;
      'page-blog-filter': LocalJSX.PageBlogFilter & JSXBase.HTMLAttributes<HTMLPageBlogFilterElement>;
      'page-books': LocalJSX.PageBooks & JSXBase.HTMLAttributes<HTMLPageBooksElement>;
      'page-cage': LocalJSX.PageCage & JSXBase.HTMLAttributes<HTMLPageCageElement>;
      'page-cmd-chron-beaver-cage': LocalJSX.PageCmdChronBeaverCage & JSXBase.HTMLAttributes<HTMLPageCmdChronBeaverCageElement>;
      'page-format-currency-in-angular': LocalJSX.PageFormatCurrencyInAngular & JSXBase.HTMLAttributes<HTMLPageFormatCurrencyInAngularElement>;
      'page-getting-parts-of-a-url-from-the-httpservletrequest-object': LocalJSX.PageGettingPartsOfAUrlFromTheHttpservletrequestObject & JSXBase.HTMLAttributes<HTMLPageGettingPartsOfAUrlFromTheHttpservletrequestObjectElement>;
      'page-index-of-item-within-angular-ngfor-loop': LocalJSX.PageIndexOfItemWithinAngularNgforLoop & JSXBase.HTMLAttributes<HTMLPageIndexOfItemWithinAngularNgforLoopElement>;
      'page-isolate-a-polygroup-in-zbrush': LocalJSX.PageIsolateAPolygroupInZbrush & JSXBase.HTMLAttributes<HTMLPageIsolateAPolygroupInZbrushElement>;
      'page-killing-kittens': LocalJSX.PageKillingKittens & JSXBase.HTMLAttributes<HTMLPageKillingKittensElement>;
      'page-list-ibm-db2-commands': LocalJSX.PageListIbmDb2Commands & JSXBase.HTMLAttributes<HTMLPageListIbmDb2CommandsElement>;
      'page-photos-weapons-platoon': LocalJSX.PagePhotosWeaponsPlatoon & JSXBase.HTMLAttributes<HTMLPagePhotosWeaponsPlatoonElement>;
      'page-pwa-with-ionic-angular-wordpress-api-1': LocalJSX.PagePwaWithIonicAngularWordpressApi1 & JSXBase.HTMLAttributes<HTMLPagePwaWithIonicAngularWordpressApi1Element>;
      'page-ray-kelley-silver-star': LocalJSX.PageRayKelleySilverStar & JSXBase.HTMLAttributes<HTMLPageRayKelleySilverStarElement>;
      'page-respond-to-button-click-with-observable': LocalJSX.PageRespondToButtonClickWithObservable & JSXBase.HTMLAttributes<HTMLPageRespondToButtonClickWithObservableElement>;
      'page-sparql-examples-ask': LocalJSX.PageSparqlExamplesAsk & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesAskElement>;
      'page-sparql-examples-construct': LocalJSX.PageSparqlExamplesConstruct & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesConstructElement>;
      'page-sparql-examples-count-all-statements': LocalJSX.PageSparqlExamplesCountAllStatements & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesCountAllStatementsElement>;
      'page-sparql-examples-date-range': LocalJSX.PageSparqlExamplesDateRange & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesDateRangeElement>;
      'page-sparql-examples-federation': LocalJSX.PageSparqlExamplesFederation & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesFederationElement>;
      'page-sparql-examples-filter': LocalJSX.PageSparqlExamplesFilter & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesFilterElement>;
      'page-sparql-examples-insert': LocalJSX.PageSparqlExamplesInsert & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesInsertElement>;
      'page-sparql-examples-limit': LocalJSX.PageSparqlExamplesLimit & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesLimitElement>;
      'page-sparql-examples-list-classes': LocalJSX.PageSparqlExamplesListClasses & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesListClassesElement>;
      'page-sparql-examples-negation': LocalJSX.PageSparqlExamplesNegation & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesNegationElement>;
      'page-sparql-examples-order-by': LocalJSX.PageSparqlExamplesOrderBy & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesOrderByElement>;
      'page-sparql-examples-paging': LocalJSX.PageSparqlExamplesPaging & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesPagingElement>;
      'page-sparql-examples-select': LocalJSX.PageSparqlExamplesSelect & JSXBase.HTMLAttributes<HTMLPageSparqlExamplesSelectElement>;
      'page-tabs': LocalJSX.PageTabs & JSXBase.HTMLAttributes<HTMLPageTabsElement>;
      'page-template-page': LocalJSX.PageTemplatePage & JSXBase.HTMLAttributes<HTMLPageTemplatePageElement>;
      'page-use-prism-js-in-ionic-stencil-app': LocalJSX.PageUsePrismJsInIonicStencilApp & JSXBase.HTMLAttributes<HTMLPageUsePrismJsInIonicStencilAppElement>;
      'page-vietnam-1967-amphibious-combat': LocalJSX.PageVietnam1967AmphibiousCombat & JSXBase.HTMLAttributes<HTMLPageVietnam1967AmphibiousCombatElement>;
      'page-zbrush-keyboard-shortcuts': LocalJSX.PageZbrushKeyboardShortcuts & JSXBase.HTMLAttributes<HTMLPageZbrushKeyboardShortcutsElement>;
    }
  }
}


