/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface PageBlog {}
  interface PageTabs {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLPageBlogElement extends Components.PageBlog, HTMLStencilElement {}
  var HTMLPageBlogElement: {
    prototype: HTMLPageBlogElement;
    new (): HTMLPageBlogElement;
  };

  interface HTMLPageTabsElement extends Components.PageTabs, HTMLStencilElement {}
  var HTMLPageTabsElement: {
    prototype: HTMLPageTabsElement;
    new (): HTMLPageTabsElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'page-blog': HTMLPageBlogElement;
    'page-tabs': HTMLPageTabsElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface PageBlog {}
  interface PageTabs {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'page-blog': PageBlog;
    'page-tabs': PageTabs;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'page-blog': LocalJSX.PageBlog & JSXBase.HTMLAttributes<HTMLPageBlogElement>;
      'page-tabs': LocalJSX.PageTabs & JSXBase.HTMLAttributes<HTMLPageTabsElement>;
    }
  }
}


